        // ── Salsa & Bachata curated tracks ──
        CuratedTrack(deezerID: 3786707482,  genre: "Latin",    title: "Como en el Idilio", artist: "Marc Anthony"),
        CuratedTrack(deezerID: 3171003001,  genre: "Latin",    title: "BAILE INoLVIDABLE", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 3773003372,  genre: "Latin",    title: "CAMBIARÉ", artist: "Luis Fonsi"),
        CuratedTrack(deezerID: 3086954711,  genre: "Latin",    title: "Cosa Nuestra", artist: "Rauw Alejandro"),
        CuratedTrack(deezerID: 429987972,  genre: "Latin",    title: "Ven Devórame Otra Vez", artist: "Lalo Rodriguez"),
        CuratedTrack(deezerID: 3725958682,  genre: "Latin",    title: "Por un Pendejo no se llora", artist: "Manuel Turizo"),
        CuratedTrack(deezerID: 3171003141,  genre: "Latin",    title: "LA MuDANZA", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 3783834412,  genre: "Latin",    title: "1+1", artist: "Maluma"),
        CuratedTrack(deezerID: 3345133651,  genre: "Latin",    title: "DROGA", artist: "Mora"),
        CuratedTrack(deezerID: 3594145862,  genre: "Latin",    title: "A CABALLO", artist: "Nathy Peluso"),
        CuratedTrack(deezerID: 3200740371,  genre: "Latin",    title: "Caramelito", artist: "Guaynaa"),
        CuratedTrack(deezerID: 2432863185,  genre: "Latin",    title: "ELLA TIENE", artist: "Nathy Peluso"),
        CuratedTrack(deezerID: 3847734401,  genre: "Latin",    title: "Mi Romi", artist: "Los Yakis"),
        CuratedTrack(deezerID: 3580630881,  genre: "Latin",    title: "La Tirana", artist: "Mon Laferte"),
        CuratedTrack(deezerID: 3677908682,  genre: "Latin",    title: "Dardos", artist: "Romeo Santos"),
        CuratedTrack(deezerID: 3628872132,  genre: "Latin",    title: "La Clave", artist: "Sergio Alejandro"),
        CuratedTrack(deezerID: 3249934031,  genre: "Latin",    title: "EROTIKA", artist: "Nathy Peluso"),
        CuratedTrack(deezerID: 3710982182,  genre: "Latin",    title: "Solo", artist: "De La Ghetto"),
        CuratedTrack(deezerID: 3012594991,  genre: "Latin",    title: "Traicionera", artist: "Daviles de Novelda"),
        CuratedTrack(deezerID: 3759550622,  genre: "Latin",    title: "Pa' Los Envidiosos", artist: "Pitbull"),
        CuratedTrack(deezerID: 2124708237,  genre: "Latin",    title: "La Fórmula", artist: "Maluma"),
        CuratedTrack(deezerID: 3310961601,  genre: "Latin",    title: "How Deep Is Your Love", artist: "Prince Royce"),
        CuratedTrack(deezerID: 3623635112,  genre: "Latin",    title: "bachata mía", artist: "Elsa y Elmar"),
        CuratedTrack(deezerID: 2747766841,  genre: "Latin",    title: "EL CANTANTE DEL GHETTO", artist: "Ryan Castro"),
        CuratedTrack(deezerID: 3713785802,  genre: "Latin",    title: "Playa Pantaleta", artist: "Rawayana"),
        CuratedTrack(deezerID: 3098627101,  genre: "Latin",    title: "Sigueme Besando Asi", artist: "Manuel Turizo"),
        CuratedTrack(deezerID: 3675376612,  genre: "Latin",    title: "Qué Tiene Él", artist: "Moa Rivera"),
        CuratedTrack(deezerID: 2965383531,  genre: "Latin",    title: "Tu Loca", artist: "NATTI NATASHA   "),
        CuratedTrack(deezerID: 1236513632,  genre: "Latin",    title: "Un Veneno", artist: "C. Tangana"),
        CuratedTrack(deezerID: 2706005432,  genre: "Latin",    title: "Brindo Con Agua", artist: "Aventura"),
        CuratedTrack(deezerID: 1507773472,  genre: "Latin",    title: "Ateo", artist: "C. Tangana"),
        CuratedTrack(deezerID: 1753549417,  genre: "Latin",    title: "La Bachata", artist: "Manuel Turizo"),
        CuratedTrack(deezerID: 2659738222,  genre: "Latin",    title: "En Esta Boca", artist: "Kany Garcia"),
        CuratedTrack(deezerID: 2610617372,  genre: "Latin",    title: "COMO YO TE QUIERO (DELUXE)", artist: "KHEA"),
        CuratedTrack(deezerID: 2131841797,  genre: "Latin",    title: "Herrera", artist: "YEИDRY"),
        CuratedTrack(deezerID: 3774754952,  genre: "Latin",    title: "Solo Tú", artist: "Valeria Jasso"),
        CuratedTrack(deezerID: 3840450261,  genre: "Latin",    title: "Bachatón", artist: "Mar Lucas"),
        CuratedTrack(deezerID: 2840850382,  genre: "Latin",    title: "Si Quieres Volver", artist: "Ralphy Dreamz"),
        CuratedTrack(deezerID: 3244282881,  genre: "Latin",    title: "Mamipuladora", artist: "Mushkaa"),
        CuratedTrack(deezerID: 114622734,  genre: "Latin",    title: "En Barranquilla Me Quedo", artist: "Joe Arroyo"),
        CuratedTrack(deezerID: 2812852392,  genre: "Latin",    title: "Quiéreme Menos", artist: "NATTI NATASHA   "),
        CuratedTrack(deezerID: 2891517542,  genre: "Latin",    title: "Dime tú", artist: "Danny Ocean"),
        CuratedTrack(deezerID: 2884478152,  genre: "Latin",    title: "Iguales y diferentes", artist: "Lorena Gomez"),
        CuratedTrack(deezerID: 2637953342,  genre: "Latin",    title: "SIN TI", artist: "GIMS"),
        CuratedTrack(deezerID: 3359783531,  genre: "Latin",    title: "samaná", artist: "Mau y Ricky"),
        CuratedTrack(deezerID: 2988957391,  genre: "Latin",    title: "Duro De Verdad pt.2", artist: "Los Sufridos"),
        CuratedTrack(deezerID: 3690691972,  genre: "Latin",    title: "ROMÁNTICA", artist: "Maria Becerra"),
        CuratedTrack(deezerID: 2732379571,  genre: "Latin",    title: "Una Vida Pasada", artist: "Camilo"),
        CuratedTrack(deezerID: 2584580172,  genre: "Latin",    title: "Ahora Que No Te Tengo", artist: "Chanel"),
        CuratedTrack(deezerID: 2169294337,  genre: "Latin",    title: "El Merengue", artist: "Marshmello"),
        CuratedTrack(deezerID: 2637475742,  genre: "Latin",    title: "UNA BACHATA", artist: "Lola Indigo"),
        CuratedTrack(deezerID: 686098802,  genre: "Latin",    title: "Pedro Navaja", artist: "Willie Colón"),
        CuratedTrack(deezerID: 2216800257,  genre: "Latin",    title: "Solo Pienso En Ti", artist: "Elvis Crespo"),
        CuratedTrack(deezerID: 3637926292,  genre: "Latin",    title: "Si Te Preguntan", artist: "Salsa Power Band"),
        CuratedTrack(deezerID: 12694767,  genre: "Latin",    title: "Y No Hago Mas Na'", artist: "El Gran Combo"),
        CuratedTrack(deezerID: 2461353085,  genre: "Latin",    title: "Rueda Durísimo", artist: "Nandy Versátil"),
        CuratedTrack(deezerID: 2276362,  genre: "Latin",    title: "La Vida Es Un Carnaval", artist: "Celia Cruz"),
        CuratedTrack(deezerID: 2511434161,  genre: "Latin",    title: "Plutón", artist: "Arcangel"),
        CuratedTrack(deezerID: 3640116732,  genre: "Latin",    title: "Bebezinho", artist: "Bianca Costa"),
        CuratedTrack(deezerID: 2122382007,  genre: "Latin",    title: "Desnúdate", artist: "Zion & Lennox"),
        CuratedTrack(deezerID: 675919592,  genre: "Latin",    title: "Parecen Viernes", artist: "Marc Anthony"),
        CuratedTrack(deezerID: 6123964,  genre: "Latin",    title: "La rebelion", artist: "Joe Arroyo"),
        CuratedTrack(deezerID: 13182317,  genre: "Latin",    title: "La Quiero A Morir", artist: "D.L.G."),
        CuratedTrack(deezerID: 547759,  genre: "Latin",    title: "Tu Amor Me Hace Bien", artist: "Marc Anthony"),
        CuratedTrack(deezerID: 686082682,  genre: "Latin",    title: "El Cantante", artist: "Héctor Lavoe"),
        CuratedTrack(deezerID: 523114932,  genre: "Latin",    title: "Me Tengo Que Ir", artist: "Los Adolescentes"),
        CuratedTrack(deezerID: 1079887762,  genre: "Latin",    title: "PURO VENENO", artist: "Nathy Peluso"),
        CuratedTrack(deezerID: 3669229822,  genre: "Latin",    title: "RAMÉ", artist: "Boza"),
        CuratedTrack(deezerID: 3911167911,  genre: "Latin",    title: "PA' LO BONITO", artist: "Lenny Tavarez"),
