        // ── Chill House (Vibe Phase) curated tracks ──
        CuratedTrack(deezerID: 3592281322, genre: "Chill", title: "Anchor", artist: "Alex Baker"),
        CuratedTrack(deezerID: 3678108442, genre: "Chill", title: "Spend The Night", artist: "Alex Adair"),
        CuratedTrack(deezerID: 3287600101, genre: "Chill", title: "A Way Back Home", artist: "Slowtide"),
        CuratedTrack(deezerID: 3607014102, genre: "Chill", title: "Morning Light", artist: "just here."),
        CuratedTrack(deezerID: 3745993542, genre: "Chill", title: "Sunday Sunrise", artist: "Martim Rola"),
        CuratedTrack(deezerID: 3631650032, genre: "Chill", title: "lemonade", artist: "gelato mac"),
        CuratedTrack(deezerID: 3698852122, genre: "Chill", title: "next chapter", artist: "bandhagen"),
        CuratedTrack(deezerID: 3750904102, genre: "Chill", title: "Nemora", artist: "Nox Vahn"),
        CuratedTrack(deezerID: 3618906412, genre: "Chill", title: "Watermark", artist: "Nora En Pure"),
        CuratedTrack(deezerID: 3564142211, genre: "Chill", title: "Take Me Down", artist: "Natascha Polke"),
        CuratedTrack(deezerID: 3631612742, genre: "Chill", title: "Drift", artist: "Echo Riviera"),
        CuratedTrack(deezerID: 3703526512, genre: "Chill", title: "Falling", artist: "Last Sun"),
        CuratedTrack(deezerID: 3825866811, genre: "Chill", title: "Feel Your Touch", artist: "P.A.V"),
        CuratedTrack(deezerID: 3613929662, genre: "Chill", title: "Chateau", artist: "Duce"),
        CuratedTrack(deezerID: 3721041452, genre: "Chill", title: "Nuage", artist: "TVLI"),
        CuratedTrack(deezerID: 3629922332, genre: "Chill", title: "Yearning For You", artist: "fwd/slash"),
        CuratedTrack(deezerID: 3606191602, genre: "Chill", title: "If You Wanna Call It Love", artist: "Francoise Sanders"),
        CuratedTrack(deezerID: 3631134632, genre: "Chill", title: "Winding Down", artist: "Sean Rivers"),
        CuratedTrack(deezerID: 3698201442, genre: "Chill", title: "New Beginnings", artist: "Iskarelyn"),
        CuratedTrack(deezerID: 3709276822, genre: "Chill", title: "Meltemi", artist: "Il:lo"),
        CuratedTrack(deezerID: 3736736552, genre: "Chill", title: "Let Go Of Your Pain", artist: "Trilucid"),
        CuratedTrack(deezerID: 3608171762, genre: "Chill", title: "Chasing Time", artist: "Aiden"),
        CuratedTrack(deezerID: 3651791682, genre: "Chill", title: "Been A While", artist: "Duce"),
        CuratedTrack(deezerID: 3614316472, genre: "Chill", title: "Can't Help It", artist: "Henry Robin"),
        CuratedTrack(deezerID: 3613930472, genre: "Chill", title: "Then & Now", artist: "Priior"),
        CuratedTrack(deezerID: 3745731172, genre: "Chill", title: "Lido", artist: "Midnight Pass"),
        CuratedTrack(deezerID: 3578182111, genre: "Chill", title: "shifted perspective", artist: "Moire"),
        CuratedTrack(deezerID: 3722226472, genre: "Chill", title: "Everywhere I Go", artist: "P.A.V"),
        CuratedTrack(deezerID: 3663920772, genre: "Chill", title: "See You", artist: "Farves"),
        CuratedTrack(deezerID: 3663225442, genre: "Chill", title: "Clapland", artist: "Extrawelt"),
        CuratedTrack(deezerID: 3721622922, genre: "Chill", title: "Be Somewhere", artist: "CLÜE"),
        CuratedTrack(deezerID: 3631217022, genre: "Chill", title: "Sunkissed", artist: "sundraze"),
        CuratedTrack(deezerID: 3660671132, genre: "Chill", title: "haunted", artist: "puulse"),
        CuratedTrack(deezerID: 3614315812, genre: "Chill", title: "Remember To Live", artist: "Oliver River"),
        CuratedTrack(deezerID: 3696987642, genre: "Chill", title: "Pressure", artist: "Jake and the colors"),
        CuratedTrack(deezerID: 3641383702, genre: "Chill", title: "Marea", artist: "Solara"),
        CuratedTrack(deezerID: 3600265682, genre: "Chill", title: "Sunday Glow", artist: "Lanle"),
        CuratedTrack(deezerID: 3537014171, genre: "Chill", title: "Sunlite", artist: "Catching Flies"),
        CuratedTrack(deezerID: 3599489412, genre: "Chill", title: "Wind Runner (Grandbrothers Remix)", artist: "Douran"),
        CuratedTrack(deezerID: 3665882992, genre: "Chill", title: "Cybèle", artist: "Grandbrothers"),
        CuratedTrack(deezerID: 3669996202, genre: "Chill", title: "Dreaming", artist: "Adryan"),
        CuratedTrack(deezerID: 3706507662, genre: "Chill", title: "Hope", artist: "Alex Breitling"),
        CuratedTrack(deezerID: 3725821692, genre: "Chill", title: "Feel It", artist: "Hobes"),
        CuratedTrack(deezerID: 3606333342, genre: "Chill", title: "Echoes", artist: "Jake and the colors"),
        CuratedTrack(deezerID: 3618069942, genre: "Chill", title: "Falling For", artist: "Because of Art"),
        CuratedTrack(deezerID: 3717139542, genre: "Chill", title: "High Tides", artist: "just here."),
        CuratedTrack(deezerID: 3612182442, genre: "Chill", title: "her certain uncertainty (edit)", artist: "Leaving Laurel"),
        CuratedTrack(deezerID: 3705006292, genre: "Chill", title: "Without You", artist: "Miravo"),
        CuratedTrack(deezerID: 3448668731, genre: "Chill", title: "Timeless", artist: "shandr"),
        CuratedTrack(deezerID: 3692997702, genre: "Chill", title: "Decay", artist: "rshand"),
        CuratedTrack(deezerID: 3736872092, genre: "Chill", title: "downtown", artist: "Aural"),
        CuratedTrack(deezerID: 3690504022, genre: "Chill", title: "Life Expected", artist: "Jasper Tygner"),
        CuratedTrack(deezerID: 3788070762, genre: "Chill", title: "Dawn", artist: "Cushy"),
        CuratedTrack(deezerID: 3625611172, genre: "Chill", title: "unsaid", artist: "Healr"),
        CuratedTrack(deezerID: 3628954892, genre: "Chill", title: "Sweep", artist: "Sébastien Léger"),
        CuratedTrack(deezerID: 3676931732, genre: "Chill", title: "Joyful Air", artist: "Berner Sen"),
        CuratedTrack(deezerID: 3453869981, genre: "Chill", title: "Her Radiance", artist: "shandr"),
        CuratedTrack(deezerID: 3675780792, genre: "Chill", title: "find myself", artist: "aelera"),
        CuratedTrack(deezerID: 3661850732, genre: "Chill", title: "dancing's done", artist: "Oliver River"),
        CuratedTrack(deezerID: 3638806462, genre: "Chill", title: "Endless Skies", artist: "Alex Breitling"),
        CuratedTrack(deezerID: 3675780592, genre: "Chill", title: "atrium", artist: "First Sun"),
        CuratedTrack(deezerID: 3706507182, genre: "Chill", title: "Another Life", artist: "D.Polo"),
        CuratedTrack(deezerID: 3646398192, genre: "Chill", title: "don't forget", artist: "nova fell"),
        CuratedTrack(deezerID: 3706503742, genre: "Chill", title: "82", artist: "Light Chaser"),
        CuratedTrack(deezerID: 3467357601, genre: "Chill", title: "Takeoff", artist: "Birrd"),
        CuratedTrack(deezerID: 3664216462, genre: "Chill", title: "Adrift", artist: "vahr"),
        CuratedTrack(deezerID: 3705617142, genre: "Chill", title: "In My Head", artist: "Cloudcage"),
        CuratedTrack(deezerID: 3664222312, genre: "Chill", title: "Clouds", artist: "Renei"),
        CuratedTrack(deezerID: 3614314382, genre: "Chill", title: "Hope", artist: "Iskarelyn"),
        CuratedTrack(deezerID: 3678514082, genre: "Chill", title: "Leaving Brixton", artist: "Mike rish"),
        CuratedTrack(deezerID: 3652154882, genre: "Chill", title: "Finding Myself", artist: "FarLight"),
        CuratedTrack(deezerID: 3650822422, genre: "Chill", title: "Aurelia", artist: "Matrx"),
        CuratedTrack(deezerID: 3650825802, genre: "Chill", title: "Wake Me Up", artist: "Passing Clouds"),
        CuratedTrack(deezerID: 3664057282, genre: "Chill", title: "Wildcard", artist: "IPeiqi"),
        CuratedTrack(deezerID: 3676097302, genre: "Chill", title: "BORDERLINE", artist: "Yuma"),
        CuratedTrack(deezerID: 3737262232, genre: "Chill", title: "Under The Moonlight", artist: "Birø"),
        CuratedTrack(deezerID: 3918368951, genre: "Chill", title: "Bosky", artist: "Mossera"),
        CuratedTrack(deezerID: 3721043762, genre: "Chill", title: "Nobody Else", artist: "Odare"),
        CuratedTrack(deezerID: 3661621202, genre: "Chill", title: "Dreamer", artist: "Aalson"),
        CuratedTrack(deezerID: 3681229602, genre: "Chill", title: "My Lexicon", artist: "Sander Kleinenberg"),
        CuratedTrack(deezerID: 3747969742, genre: "Chill", title: "Nisramont", artist: "Brendel"),
        CuratedTrack(deezerID: 3664216822, genre: "Chill", title: "For U", artist: "YVMV"),
        CuratedTrack(deezerID: 3721047482, genre: "Chill", title: "Forever", artist: "Rytes"),
        CuratedTrack(deezerID: 3643790902, genre: "Chill", title: "Daydreaming", artist: "Nordsky"),
        CuratedTrack(deezerID: 3642360222, genre: "Chill", title: "Somebody", artist: "Bjarne Hendrik"),
        CuratedTrack(deezerID: 3706509362, genre: "Chill", title: "From Here", artist: "Seawyn"),
        CuratedTrack(deezerID: 3638806452, genre: "Chill", title: "closure", artist: "overuu"),
        CuratedTrack(deezerID: 3706503112, genre: "Chill", title: "Next To Me", artist: "Passing Clouds"),
        CuratedTrack(deezerID: 3693002332, genre: "Chill", title: "Touch", artist: "itsgreat"),
        CuratedTrack(deezerID: 3721468472, genre: "Chill", title: "Celebration", artist: "The Meridian"),
        CuratedTrack(deezerID: 3647700402, genre: "Chill", title: "Twin Towers", artist: "Dinka"),
        CuratedTrack(deezerID: 3706503992, genre: "Chill", title: "Stepping Into Paradise", artist: "BARELO"),
        CuratedTrack(deezerID: 3676932502, genre: "Chill", title: "This Dance", artist: "Meladonica"),
        CuratedTrack(deezerID: 3661661352, genre: "Chill", title: "It's Okay", artist: "GÆO"),
        CuratedTrack(deezerID: 3735751232, genre: "Chill", title: "I Think The Universe Blinked", artist: "Mimin"),
        CuratedTrack(deezerID: 3519037591, genre: "Chill", title: "Above The Clouds", artist: "Plutones"),
        CuratedTrack(deezerID: 3674012782, genre: "Chill", title: "Embers", artist: "Udipta"),
        CuratedTrack(deezerID: 3883623081, genre: "Chill", title: "The Light", artist: "Viken Arman"),
        CuratedTrack(deezerID: 3710459472, genre: "Chill", title: "Whispers of Heaven", artist: "The Abrame"),
        CuratedTrack(deezerID: 3634755652, genre: "Chill", title: "Home (Tor Remix)", artist: "Noé Solange"),
