        // ── Fuego Latino curated tracks ──
        CuratedTrack(deezerID: 3871739701,  genre: "Pop",    title: "ALGO TÚ", artist: "Shakira"),
        CuratedTrack(deezerID: 3865096921,  genre: "Reggaeton",    title: "Tonto", artist: "J Balvin"),
        CuratedTrack(deezerID: 3171002981,  genre: "Reggaeton",    title: "NUEVAYoL", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 3889748961,  genre: "Latin",    title: "Jamaican (Bam Bam)", artist: "HUGEL"),
        CuratedTrack(deezerID: 4015341011,  genre: "Pop",    title: "Dai Dai", artist: "Shakira"),
        CuratedTrack(deezerID: 3981853831,  genre: "Latin",    title: "LA GRACIOSA", artist: "Quevedo"),
        CuratedTrack(deezerID: 3421452651,  genre: "Reggaeton",    title: "Tropicoqueta", artist: "KAROL G"),
        CuratedTrack(deezerID: 3171003131,  genre: "Reggaeton",    title: "DtMF", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 3879862701,  genre: "Latin",    title: "PONGO", artist: "Rvssian"),
        CuratedTrack(deezerID: 3241972661,  genre: "Latin",    title: "La Plena (W Sound 05)", artist: "W Sound"),
        CuratedTrack(deezerID: 3879273701,  genre: "Reggaeton",    title: "Una Aventura", artist: "Ozuna"),
        CuratedTrack(deezerID: 3936484551,  genre: "Latin",    title: "BIAF <3", artist: "Young Miko"),
        CuratedTrack(deezerID: 3407512021,  genre: "Latin",    title: "TU VAS SIN (fav)", artist: "Rels B"),
        CuratedTrack(deezerID: 3171003121,  genre: "Reggaeton",    title: "EoO", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 3920012581,  genre: "Reggaeton",    title: "Pal Agua", artist: "J Balvin"),
        CuratedTrack(deezerID: 3849394771,  genre: "Latin",    title: "Ayer La Vi (BPA26)", artist: "Juan Magan"),
        CuratedTrack(deezerID: 3663852612,  genre: "Pop",    title: "Hips Don't Lie", artist: "Shakira"),
        CuratedTrack(deezerID: 2638201552,  genre: "Latin",    title: "Gata Only", artist: "FloyyMenor"),
        CuratedTrack(deezerID: 3638389092,  genre: "Reggaeton",    title: "Daddy Yankee: Bzrp Music Sessions, Vol. 0/66", artist: "Bizarrap"),
        CuratedTrack(deezerID: 3640140952,  genre: "Reggaeton",    title: "La Perla", artist: "ROSALÍA"),
        CuratedTrack(deezerID: 3947383241,  genre: "Latin",    title: "De Lejitos", artist: "Jay Wheeler"),
        CuratedTrack(deezerID: 3421452481,  genre: "Reggaeton",    title: "Papasito", artist: "KAROL G"),
        CuratedTrack(deezerID: 3713785742,  genre: "Latin",    title: "Inglés En Miami", artist: "Rawayana"),
        CuratedTrack(deezerID: 3348923451,  genre: "Latin",    title: "malibU", artist: "Rusowsky"),
        CuratedTrack(deezerID: 3905162121,  genre: "Latin",    title: "Pinterest (Spanish)", artist: "Anitta"),
        CuratedTrack(deezerID: 3909037631,  genre: "Latin",    title: "TRANKAITO", artist: "Feid"),
        CuratedTrack(deezerID: 3171003021,  genre: "Reggaeton",    title: "WELTiTA", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 3862522561,  genre: "Latin",    title: "Apambichao", artist: "Manuel Turizo"),
        CuratedTrack(deezerID: 3086954731,  genre: "Reggaeton",    title: "Qué Pasaría...", artist: "Rauw Alejandro"),
        CuratedTrack(deezerID: 3829058471,  genre: "Latin",    title: "Choque", artist: "Bad Gyal"),
        CuratedTrack(deezerID: 3729422322,  genre: "Latin",    title: "daño", artist: "Peso Pluma"),
        CuratedTrack(deezerID: 3380325281,  genre: "Latin",    title: "SUPERESTRELLA", artist: "Aitana"),
        CuratedTrack(deezerID: 3729422272,  genre: "Latin",    title: "dopamina", artist: "Peso Pluma"),
        CuratedTrack(deezerID: 3393136571,  genre: "Latin",    title: "Shiny", artist: "Easykid"),
        CuratedTrack(deezerID: 2403815945,  genre: "Reggaeton",    title: "QLONA", artist: "KAROL G"),
        CuratedTrack(deezerID: 2496106371,  genre: "Reggaeton",    title: "MONACO", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 3619889162,  genre: "Reggaeton",    title: "Berghain", artist: "ROSALÍA"),
        CuratedTrack(deezerID: 3210670571,  genre: "Latin",    title: "ROMEO", artist: "Anitta"),
        CuratedTrack(deezerID: 2846442802,  genre: "Reggaeton",    title: "Si Antes Te Hubiera Conocido", artist: "KAROL G"),
        CuratedTrack(deezerID: 3721301952,  genre: "Latin",    title: "Muévelo", artist: "Kali Uchis"),
        CuratedTrack(deezerID: 3562510031,  genre: "Latin",    title: "Bodega Baddie", artist: "Cardi B"),
        CuratedTrack(deezerID: 2381974745,  genre: "Latin",    title: "Una Noche en Medellín", artist: "Cris MJ"),
        CuratedTrack(deezerID: 3353337101,  genre: "Latin",    title: "no tiene sentido", artist: "Beele"),
        CuratedTrack(deezerID: 3005912441,  genre: "Latin",    title: "Cuando No Era Cantante", artist: "El Bogueto"),
        CuratedTrack(deezerID: 2154046577,  genre: "Reggaeton",    title: "AMARGURA", artist: "KAROL G"),
        CuratedTrack(deezerID: 3613707422,  genre: "Latin",    title: "LA VILLA", artist: "Ryan Castro"),
        CuratedTrack(deezerID: 3694837562,  genre: "Latin",    title: "HOY SE GUAYA", artist: "Arcangel"),
        CuratedTrack(deezerID: 2565307142,  genre: "Latin",    title: "LUNA", artist: "Feid"),
        CuratedTrack(deezerID: 2725148591,  genre: "Latin",    title: "Santa", artist: "Rvssian"),
        CuratedTrack(deezerID: 3431134971,  genre: "Electro",    title: "Noventa", artist: "DJ Snake"),
        CuratedTrack(deezerID: 3729101662,  genre: "Latin",    title: "Ay Dale", artist: "Farruko"),
        CuratedTrack(deezerID: 3086954821,  genre: "Reggaeton",    title: "Khé?", artist: "Rauw Alejandro"),
        CuratedTrack(deezerID: 2710627572,  genre: "Latin",    title: "DUMBAI", artist: "CA7RIEL & Paco Amoroso"),
        CuratedTrack(deezerID: 3348923391,  genre: "Latin",    title: "Johnny Glamour", artist: "Rusowsky"),
        CuratedTrack(deezerID: 3543288831,  genre: "Latin",    title: "Posso Até Não Te Dar Flores", artist: "DJ Japa NK"),
        CuratedTrack(deezerID: 3346909081,  genre: "Latin",    title: "Vaitimbora", artist: "Trinix"),
        CuratedTrack(deezerID: 3644302002,  genre: "Latin",    title: "lençóis maranhenses", artist: "Beele"),
        CuratedTrack(deezerID: 2352913965,  genre: "Reggaeton",    title: "DILUVIO", artist: "Rauw Alejandro"),
        CuratedTrack(deezerID: 3002724121,  genre: "Pop",    title: "Soltera", artist: "Shakira"),
        CuratedTrack(deezerID: 3100867631,  genre: "Latin",    title: "mi refe", artist: "Beele"),
        CuratedTrack(deezerID: 3184783941,  genre: "Latin",    title: "Corazón Puro", artist: "Rvfv"),
        CuratedTrack(deezerID: 668529022,  genre: "Latin",    title: "La Cartera", artist: "Farruko"),
        CuratedTrack(deezerID: 3128448851,  genre: "Reggaeton",    title: "EL CLúB", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 2352899405,  genre: "Latin",    title: "QUEMA", artist: "Ryan Castro"),
        CuratedTrack(deezerID: 2454704515,  genre: "Latin",    title: "BUBALU", artist: "Feid"),
        CuratedTrack(deezerID: 3080231821,  genre: "Latin",    title: "capaz (merengueton)", artist: "alleh"),
        CuratedTrack(deezerID: 3177818391,  genre: "Latin",    title: "Angelito", artist: "Bad Gyal"),
        CuratedTrack(deezerID: 2971960441,  genre: "Latin",    title: "Alibi Pt. 2 (with Anitta, Pabllo Vittar & Yseult)", artist: "Sevdaliza"),
        CuratedTrack(deezerID: 3644297482,  genre: "Electro",    title: "GUAYANDO", artist: "Major Lazer"),
        CuratedTrack(deezerID: 2986885311,  genre: "Latin",    title: "Después De La 1", artist: "Cris MJ"),
        CuratedTrack(deezerID: 3104740921,  genre: "Latin",    title: "SHIBATTO", artist: "Quevedo"),
        CuratedTrack(deezerID: 3061738201,  genre: "Latin",    title: "Imagínate", artist: "Danny Ocean"),
        CuratedTrack(deezerID: 3070117621,  genre: "Reggaeton",    title: "Cosas Pendientes", artist: "Maluma"),
        CuratedTrack(deezerID: 3654880132,  genre: "Latin",    title: "1204", artist: "De la rose"),
        CuratedTrack(deezerID: 2927624581,  genre: "Latin",    title: "TAMBIÉN", artist: "Myke Towers"),
        CuratedTrack(deezerID: 2788486652,  genre: "Latin",    title: "REAL GANGSTA LOVE", artist: "Trueno"),
        CuratedTrack(deezerID: 2925907271,  genre: "Latin",    title: "Alegría", artist: "Tiago PZK"),
        CuratedTrack(deezerID: 2824575332,  genre: "Latin",    title: "OHNANA", artist: "Kapo"),
        CuratedTrack(deezerID: 3064639361,  genre: "Latin",    title: "Bing Bong", artist: "Yailin la Mas Viral"),
        CuratedTrack(deezerID: 3003099991,  genre: "Latin",    title: "Q U E V A S H A C E R H O Y ?", artist: "Omar Courtz"),
        CuratedTrack(deezerID: 3345133671,  genre: "Latin",    title: "AURORA", artist: "Mora"),
        CuratedTrack(deezerID: 2570877172,  genre: "Latin",    title: "BELLAKEO", artist: "Peso Pluma"),
        CuratedTrack(deezerID: 3079892761,  genre: "Latin",    title: "Pa’ Qué Volviste?", artist: "Elena Rose"),
        CuratedTrack(deezerID: 2164743217,  genre: "Latin",    title: "La Bebe (Remix)", artist: "Yng Lvcas"),
        CuratedTrack(deezerID: 3145770261,  genre: "Latin",    title: "una noche", artist: "alleh"),
        CuratedTrack(deezerID: 2074439067,  genre: "Latin",    title: "Yandel 150", artist: "Yandel"),
        CuratedTrack(deezerID: 2595262972,  genre: "Latin",    title: "Una Foto Remix (feat. Emilia)", artist: "Mesita"),
        CuratedTrack(deezerID: 2758436071,  genre: "Latin",    title: "ADIVINO", artist: "Myke Towers"),
        CuratedTrack(deezerID: 1811481707,  genre: "Latin",    title: "Quevedo: Bzrp Music Sessions, Vol. 52/66", artist: "Bizarrap"),
        CuratedTrack(deezerID: 2496106541,  genre: "Reggaeton",    title: "PERRO NEGRO", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 3024269221,  genre: "Latin",    title: "Qué Pecao", artist: "Manuel Turizo"),
        CuratedTrack(deezerID: 3210598411,  genre: "Latin",    title: "São Paulo", artist: "The Weeknd"),
        CuratedTrack(deezerID: 2835962342,  genre: "Latin",    title: "LA REINA", artist: "Lola Indigo"),
        CuratedTrack(deezerID: 2729119091,  genre: "Latin",    title: "offline", artist: "Young Miko"),
        CuratedTrack(deezerID: 2939590111,  genre: "Latin",    title: "UWAIE", artist: "Kapo"),
        CuratedTrack(deezerID: 1917168057,  genre: "Reggaeton",    title: "PUNTO 40", artist: "Rauw Alejandro"),
        CuratedTrack(deezerID: 3524679161,  genre: "Latin",    title: "COMO OREO", artist: "Blessd"),
        CuratedTrack(deezerID: 3422751531,  genre: "Latin",    title: "Me Mareo", artist: "Kidd Voodoo"),
        CuratedTrack(deezerID: 3382134521,  genre: "Latin",    title: "YO y TÚ", artist: "Ovy On The Drums"),
        CuratedTrack(deezerID: 3739682752,  genre: "Reggaeton",    title: "J Balvin: Bzrp Music Sessions, Vol. 62/66", artist: "Bizarrap"),
