    // ★ THE ULTIMATE SOCIALMIX CATALOGUE (Generated from Batches 1-10) ★
    private let curatedTracks: [CuratedTrack] = [
        CuratedTrack(deezerID: 3833827681, genre: "House", title: "Us Humans (Mixed)", artist: "Andrea Terrano"),
        CuratedTrack(deezerID: 3833827561, genre: "House", title: "Yukon (Mixed)", artist: "BetejayMadeIt"),
        CuratedTrack(deezerID: 3833827601, genre: "House", title: "Prevail (Prelude [Mixed])", artist: "Ethiopian Chyld"),
        CuratedTrack(deezerID: 428558022, genre: "Afro", title: "Who Mad Again", artist: "Jahyanai"),
        CuratedTrack(deezerID: 1644464022, genre: "Afro", title: "Calm Down", artist: "Rema"),
        CuratedTrack(deezerID: 1998772137, genre: "Afro", title: "Tiki Taka", artist: "Vacra"),
        CuratedTrack(deezerID: 2536600371, genre: "Afro", title: "XOXO", artist: "Vacra"),
        CuratedTrack(deezerID: 561836, genre: "Pop", title: "Sweet Dreams", artist: "Eurythmics"),
        CuratedTrack(deezerID: 3833827551, genre: "House", title: "Oblivion (Mixed)", artist: "A Vision of Panorama & Meora"),
        CuratedTrack(deezerID: 3833827531, genre: "House", title: "The Floating Sun (Mixed)", artist: "Café del Mar"),
        CuratedTrack(deezerID: 3833827621, genre: "House", title: "Café Del Mar (Mixed)", artist: "Faunabeats, Café del Mar & Gelka"),
        CuratedTrack(deezerID: 3833827701, genre: "House", title: "Body Language (Mixed)", artist: "Jamie Myerson"),
        CuratedTrack(deezerID: 3833827591, genre: "House", title: "Sueños Soleados (Mixed)", artist: "John Beltran"),
        CuratedTrack(deezerID: 3833827631, genre: "House", title: "Fraude (Mixed)", artist: "Mark Moon"),
        CuratedTrack(deezerID: 3833827651, genre: "House", title: "Spare a Minute (Mixed)", artist: "Meltonix"),
        CuratedTrack(deezerID: 3833827641, genre: "House", title: "Dreamer (Mixed)", artist: "Pig&Dan & Café del Mar"),
        CuratedTrack(deezerID: 3833827661, genre: "House", title: "Second Vision (Mixed)", artist: "Pour Deux"),
        CuratedTrack(deezerID: 3833827691, genre: "House", title: "The Calling ([Mixed] Freeman Remix)", artist: "Pressure Drop"),
        CuratedTrack(deezerID: 3833827581, genre: "House", title: "Fly Away (Mixed)", artist: "Tech Support & Asa Tate"),
        CuratedTrack(deezerID: 3833827711, genre: "House", title: "Platform (Mixed)", artist: "Visions of Light"),
        CuratedTrack(deezerID: 2463390575, genre: "COCOVARIET", title: "Celui qui part", artist: "Joseph Kamel"),
        CuratedTrack(deezerID: 2470627425, genre: "Pop", title: "Why Do the Bad Things Feel Good", artist: "Marina Kaye"),
        CuratedTrack(deezerID: 1940930987, genre: "COCOVARIET", title: "Mamma Mia", artist: "Mentissa"),
        CuratedTrack(deezerID: 2000225817, genre: "COCOVARIET", title: "Mercredi", artist: "Pierre de Maere"),
        CuratedTrack(deezerID: 8, genre: "COCOVARIET", title: "94 - Stéphane - Mieux comme ça _ (feat. Petit K)", artist: "Stéphane - Mieux comme ça _ (feat. Petit K)"),
        CuratedTrack(deezerID: 2389689175, genre: "COCOVARIET", title: "Comment on fait", artist: "Vianney"),
        CuratedTrack(deezerID: 2125799387, genre: "COCOVARIET", title: "Le feu", artist: "Vianney"),
        CuratedTrack(deezerID: 2389689205, genre: "COCOVARIET", title: "Il faudrait", artist: "Vianney"),
        CuratedTrack(deezerID: 884041, genre: "Disco", title: "Gimme! Gimme! Gimme!", artist: "ABBA"),
        CuratedTrack(deezerID: 757201022, genre: "Disco", title: "Don't Stop", artist: "Asso"),
        CuratedTrack(deezerID: 8014711, genre: "Disco", title: "Nights (Feel Like Getting Down)", artist: "Billy Ocean"),
        CuratedTrack(deezerID: 1736104637, genre: "Disco", title: "Let's Start The Dance (Remix)", artist: "Bohannon Feat. Dr. Perri Johnson"),
        CuratedTrack(deezerID: 3409416781, genre: "Disco", title: "Sunny", artist: "Boney M."),
        CuratedTrack(deezerID: 11626680, genre: "Disco", title: "Do You Really Love Me", artist: "Bryan Loren"),
        CuratedTrack(deezerID: 1490273502, genre: "Disco", title: "Don't You Wanna Make Love", artist: "Carl Carlton"),
        CuratedTrack(deezerID: 445812132, genre: "Disco", title: "Supernature", artist: "Cerrone"),
        CuratedTrack(deezerID: 7, genre: "Electro", title: "da funk_ancien2", artist: "daft punk"),
        CuratedTrack(deezerID: 66609426, genre: "Disco", title: "Get Lucky", artist: "Daft Punk"),
        CuratedTrack(deezerID: 1912568, genre: "Disco", title: "Stand Up (Reach For The Sky)", artist: "Delegation"),
        CuratedTrack(deezerID: 3822044, genre: "Disco", title: "Long Train Runnin'", artist: "Doobie Brothers"),
        CuratedTrack(deezerID: 3578491641, genre: "Disco", title: "Way Out", artist: "Dynasty"),
        CuratedTrack(deezerID: 487484142, genre: "Disco", title: "September", artist: "Earth Wind & Fire"),
        CuratedTrack(deezerID: 611346, genre: "Disco", title: "Boogie Wonderland", artist: "Earth Wind & Fire"),
        CuratedTrack(deezerID: 70096742, genre: "Disco", title: "Now I'm Fine", artist: "Grey & Hanks"),
        CuratedTrack(deezerID: 2175124797, genre: "Disco", title: "Half The Day's Gone And We Haven't Earned A Penny", artist: "Kenny Lynch"),
        CuratedTrack(deezerID: 94556154, genre: "Disco", title: "Get Down On It", artist: "Kool & The Gang"),
        CuratedTrack(deezerID: 3750788562, genre: "Disco", title: "Dreamin'", artist: "Loleatta Holloway"),
        CuratedTrack(deezerID: 3786380072, genre: "Disco", title: "Wet My Whistle", artist: "Midnight Star"),
        CuratedTrack(deezerID: 559415, genre: "Disco", title: "Going Back To My Roots", artist: "Odyssey"),
        CuratedTrack(deezerID: 891347, genre: "Disco", title: "Taj Mahal", artist: "Paulinho Da Costa"),
        CuratedTrack(deezerID: 346967941, genre: "Disco", title: "I'm So Excited", artist: "Pointer Sisters"),
        CuratedTrack(deezerID: 636405, genre: "Pop", title: "Sarà perché ti amo", artist: "Ricchi e Poveri"),
        CuratedTrack(deezerID: 5448329, genre: "Disco", title: "Friends", artist: "Shalamar"),
        CuratedTrack(deezerID: 67800556, genre: "Disco", title: "Over And Over", artist: "Sylvester"),
        CuratedTrack(deezerID: 2285438237, genre: "House", title: "The Rapture Pt.III", artist: "&ME"),
        CuratedTrack(deezerID: 1269301652, genre: "House", title: "Discoteca", artist: "&ME"),
        CuratedTrack(deezerID: 365770611, genre: "House", title: "Introduction", artist: "Aaron Baron"),
        CuratedTrack(deezerID: 1746618207, genre: "House", title: "Forms Of Love", artist: "Adam Port"),
        CuratedTrack(deezerID: 2161608057, genre: "House", title: "Waves & Wavs", artist: "Ahmed Spins"),
        CuratedTrack(deezerID: 1594457231, genre: "House", title: "Reborn", artist: "arodes"),
        CuratedTrack(deezerID: 1000999382, genre: "Electro", title: "Wake Me Up (Radio Edit)", artist: "Avicii"),
        CuratedTrack(deezerID: 82398692, genre: "Electro", title: "Zouka", artist: "Bang La Decks"),
        CuratedTrack(deezerID: 795642332, genre: "House", title: "Glue", artist: "Bicep"),
        CuratedTrack(deezerID: 3045968591, genre: "House", title: "Wizard of Love", artist: "Blond:ish"),
        CuratedTrack(deezerID: 2101999797, genre: "House", title: "Sete", artist: "Blond:ish"),
        CuratedTrack(deezerID: 2680113092, genre: "House", title: "Adore", artist: "Bob Sinclar"),
        CuratedTrack(deezerID: 2634178712, genre: "House", title: "Rock This Party (Everybody Dance Now)", artist: "Bob Sinclar feat. Cutee B"),
        CuratedTrack(deezerID: 2357139175, genre: "Electro", title: "Desire", artist: "Calvin Harris"),
        CuratedTrack(deezerID: 7624161, genre: "House", title: "missing you [ft. novel]", artist: "david guetta"),
        CuratedTrack(deezerID: 3, genre: "Electro", title: "Hey Mama (feat. Nicki Minaj, Bebe Rexha & Afrojack)", artist: "David Guetta"),
        CuratedTrack(deezerID: 15583799, genre: "House", title: "You Are My High (2024 Remastered)", artist: "Demon"),
        CuratedTrack(deezerID: 487281862, genre: "House", title: "Paradon", artist: "Denis Horvat"),
        CuratedTrack(deezerID: 1613981692, genre: "Pop", title: "Can't Get You Out Of My Head", artist: "Desire"),
        CuratedTrack(deezerID: 67, genre: "Electro", title: "24 - Diala - Opiacés", artist: "Diala - Opiacés"),
        CuratedTrack(deezerID: 2570206672, genre: "House", title: "More Amor Por Favor", artist: "Dylan Linde"),
        CuratedTrack(deezerID: 7117058, genre: "House", title: "Calabria 2007", artist: "Enur ft. Natasja"),
        CuratedTrack(deezerID: 2562451692, genre: "House", title: "Voyage Voyage", artist: "Francis Mercier"),
        CuratedTrack(deezerID: 3190936781, genre: "Pop", title: "Tout le monde est fou", artist: "Jain"),
        CuratedTrack(deezerID: 2877290402, genre: "House", title: "Ven Pa Ca", artist: "Joezi"),
        CuratedTrack(deezerID: 2508240851, genre: "Pop", title: "Strangers", artist: "Kenya Grace"),
        CuratedTrack(deezerID: 4631883, genre: "House", title: "2000 - Madhouse-like a prayer", artist: "Madhouse-like a prayer"),
        CuratedTrack(deezerID: 569166552, genre: "Electro", title: "Light It Up (Feat. Nyla)", artist: "Major Lazer"),
        CuratedTrack(deezerID: 2670522762, genre: "House", title: "Opera", artist: "Marasi"),
        CuratedTrack(deezerID: 2365023705, genre: "Electro", title: "Boyz In Paris (with VINAI)", artist: "Marnik"),
        CuratedTrack(deezerID: 3230816611, genre: "House", title: "Your Body", artist: "Marten Lou"),
        CuratedTrack(deezerID: 2008609407, genre: "House", title: "Dare Your Move", artist: "MAXI MERAKI"),
        CuratedTrack(deezerID: 2569218732, genre: "House", title: "Verona", artist: "Mili"),
        CuratedTrack(deezerID: 2486813731, genre: "Electro", title: "More Love", artist: "Moderat"),
        CuratedTrack(deezerID: 1915841017, genre: "House", title: "Palomar", artist: "Monkey Safari"),
        CuratedTrack(deezerID: 2405566435, genre: "House", title: "Paris", artist: "Mont Rouge"),
        CuratedTrack(deezerID: 3311117271, genre: "House", title: "Belsunce", artist: "Mont Rouge"),
        CuratedTrack(deezerID: 2233638217, genre: "House", title: "Spacer", artist: "Mooglie"),
        CuratedTrack(deezerID: 2343066935, genre: "House", title: "Secret ID", artist: "Moojo"),
        CuratedTrack(deezerID: 3748159, genre: "Electro", title: "Flat Beat", artist: "Mr.Oizo"),
        CuratedTrack(deezerID: 2185516347, genre: "House", title: "Juno Love", artist: "Nico Morano"),
        CuratedTrack(deezerID: 2525458421, genre: "House", title: "Emowe", artist: "Notre Dame"),
        CuratedTrack(deezerID: 2472322121, genre: "Electro", title: "Overdrive (feat. Norma Jean Martine)", artist: "Ofenbach"),
        CuratedTrack(deezerID: 3408657731, genre: "Electro", title: "Make Me Feel", artist: "oskar med k"),
        CuratedTrack(deezerID: 1512797952, genre: "House", title: "Before", artist: "Pablo Fierro"),
        CuratedTrack(deezerID: 69956741, genre: "House", title: "Doo Doo Wap", artist: "Paul Johnson"),
        CuratedTrack(deezerID: 2274284527, genre: "Pop", title: "Another Song To Myself", artist: "Picture This"),
        CuratedTrack(deezerID: 2428475985, genre: "Disco", title: "Favourite Game", artist: "Rae & Christian"),
        CuratedTrack(deezerID: 2642151722, genre: "House", title: "Famax", artist: "RAFFA GUIDO"),
        CuratedTrack(deezerID: 1892122097, genre: "House", title: "Les Gout", artist: "Rampa"),
        CuratedTrack(deezerID: 2692106502, genre: "House", title: "Contigo", artist: "REBRN"),
        CuratedTrack(deezerID: 2515453531, genre: "Electro", title: "Change This Pain For Ecstasy", artist: "Rex the Dog"),
        CuratedTrack(deezerID: 113475002, genre: "House", title: "Innerbloom", artist: "RÜFÜS DU SOL"),
        CuratedTrack(deezerID: 1741718587, genre: "House", title: "Sala Papa Ye", artist: "Soulroots"),
        CuratedTrack(deezerID: 2309134745, genre: "Electro", title: "God Is A Girl", artist: "Sound Of Legend"),
        CuratedTrack(deezerID: 1787557067, genre: "House", title: "Moth To A Flame", artist: "Swedish House Mafia"),
        CuratedTrack(deezerID: 2234892777, genre: "House", title: "Emorio", artist: "Trinix"),
        CuratedTrack(deezerID: 108329720, genre: "House", title: "Do it", artist: "Trouble men"),
        CuratedTrack(deezerID: 2184848677, genre: "House", title: "Yakalongo", artist: "Ugo Banchi"),
        CuratedTrack(deezerID: 2, genre: "Electro", title: "101-the_pussycat_dolls-when_i_grow_up", artist: "Unknown"),
        CuratedTrack(deezerID: 47, genre: "Electro", title: "108-desaparecidos_vs_walter_master_j-ibiza", artist: "Unknown"),
        CuratedTrack(deezerID: 2339030005, genre: "House", title: "Résiste", artist: "Yann Muller"),
        CuratedTrack(deezerID: 3409146481, genre: "House", title: "Je dois m'en aller", artist: "Yann Muller"),
        CuratedTrack(deezerID: 1923908287, genre: "House", title: "Seventh Street", artist: "Zac"),
        CuratedTrack(deezerID: 2378226775, genre: "Hip-Hop", title: "Rooftop (feat. Robin)", artist: "47Ter"),
        CuratedTrack(deezerID: 1794017907, genre: "Hip-Hop", title: "Dernière", artist: "Bigflo & Oli"),
        CuratedTrack(deezerID: 923495502, genre: "Reggaeton", title: "MAMACITA", artist: "Black Eyed Peas"),
        CuratedTrack(deezerID: 870821062, genre: "Hip-Hop", title: "La Haine", artist: "Cut Killer"),
        CuratedTrack(deezerID: 1761408177, genre: "Reggaeton", title: "Daddy Yankee feat Lloyd Banks and Young Buck- Rompe (Remix)", artist: "Daddy Yankee"),
        CuratedTrack(deezerID: 2607111392, genre: "Hip-Hop", title: "Capitaine", artist: "Djadja & Dinaz"),
        CuratedTrack(deezerID: 2387373015, genre: "Hip-Hop", title: "Paint The Town Red", artist: "Doja Cat"),
        CuratedTrack(deezerID: 128743595, genre: "Hip-Hop", title: "The Next Episode", artist: "Dr. Dre"),
        CuratedTrack(deezerID: 128743581, genre: "Hip-Hop", title: "Still D.R.E.", artist: "Dr. Dre"),
        CuratedTrack(deezerID: 124603270, genre: "Hip-Hop", title: "One Dance", artist: "Drake"),
        CuratedTrack(deezerID: 916424, genre: "Hip-Hop", title: "Without Me", artist: "Eminem"),
        CuratedTrack(deezerID: 1109731, genre: "Hip-Hop", title: "Lose Yourself", artist: "Eminem"),
        CuratedTrack(deezerID: 9849814, genre: "Hip-Hop", title: "Be Faithful", artist: "Fatman Scoop"),
        CuratedTrack(deezerID: 2150767297, genre: "Hip-Hop", title: "Nocif", artist: "Hamza"),
        CuratedTrack(deezerID: 1584589772, genre: "Hip-Hop", title: "Jump Around", artist: "House of Pain"),
        CuratedTrack(deezerID: 2486148031, genre: "Hip-Hop", title: "Pretty Girl", artist: "Ice Spice"),
        CuratedTrack(deezerID: 2500843671, genre: "Hip-Hop", title: "Les Flammes", artist: "Josman"),
        CuratedTrack(deezerID: 2279800907, genre: "Hip-Hop", title: "La faille", artist: "Jul"),
        CuratedTrack(deezerID: 2525649041, genre: "Hip-Hop", title: "J'fais que danser", artist: "Jul"),
        CuratedTrack(deezerID: 2550505012, genre: "Hip-Hop", title: "Sensations", artist: "Jul"),
        CuratedTrack(deezerID: 2536642561, genre: "Hip-Hop", title: "Mobalpa", artist: "Kaaris"),
        CuratedTrack(deezerID: 2154046487, genre: "Reggaeton", title: "TQG", artist: "KAROL G"),
        CuratedTrack(deezerID: 2440390415, genre: "Hip-Hop", title: "LAISSE MOI", artist: "KeBlack"),
        CuratedTrack(deezerID: 1056838, genre: "Hip-Hop", title: "Jump", artist: "Kris Kross"),
        CuratedTrack(deezerID: 2330156075, genre: "Hip-Hop", title: "Reste en Vie", artist: "Luidji"),
        CuratedTrack(deezerID: 3788177632, genre: "Hip-Hop", title: "Au suivant", artist: "Lynda"),
        CuratedTrack(deezerID: 61424045, genre: "Hip-Hop", title: "Thrift Shop", artist: "Macklemore"),
        CuratedTrack(deezerID: 61424044, genre: "Hip-Hop", title: "Can't Hold Us", artist: "Macklemore & Ryan Lewis feat. Ray Dalton"),
        CuratedTrack(deezerID: 2525070311, genre: "Hip-Hop", title: "Akatsuki", artist: "Maes"),
        CuratedTrack(deezerID: 2004920127, genre: "Hip-Hop", title: "Fetty Wap", artist: "Maes"),
        CuratedTrack(deezerID: 2047662477, genre: "Hip-Hop", title: "Creepin'", artist: "Metro Boomin"),
        CuratedTrack(deezerID: 2303767705, genre: "Hip-Hop", title: "1,2,3 Soleil", artist: "Naza"),
        CuratedTrack(deezerID: 38, genre: "Hip-Hop", title: "43 - Negrito - J'ai Payé", artist: "Negrito - J'ai Payé"),
        CuratedTrack(deezerID: 3616651, genre: "Hip-Hop", title: "Hypnotize", artist: "Notorious B.I.G."),
        CuratedTrack(deezerID: 2492986081, genre: "Hip-Hop", title: "SAY MY GRACE", artist: "Offset"),
        CuratedTrack(deezerID: 2324042205, genre: "Hip-Hop", title: "Summer Party (Edit)", artist: "Olupellar"),
        CuratedTrack(deezerID: 1940385147, genre: "Hip-Hop", title: "Lola", artist: "RK"),
        CuratedTrack(deezerID: 2081099267, genre: "Hip-Hop", title: "Mr. Ocho", artist: "SDM"),
        CuratedTrack(deezerID: 2081099277, genre: "Hip-Hop", title: "Bolide allemand", artist: "SDM"),
        CuratedTrack(deezerID: 2674130352, genre: "Hip-Hop", title: "Coco & Chanel", artist: "SenSey'"),
        CuratedTrack(deezerID: 2352206125, genre: "Hip-Hop", title: "Casanova", artist: "Soolking"),
        CuratedTrack(deezerID: 2482275341, genre: "Hip-Hop", title: "La Loupe", artist: "Were Vana"),
        CuratedTrack(deezerID: 2459444615, genre: "Hip-Hop", title: "Tu connais", artist: "Werenoi"),
        CuratedTrack(deezerID: 3023551771, genre: "Hip-Hop", title: "Chemin d'or", artist: "Werenoi"),
        CuratedTrack(deezerID: 2477249181, genre: "Hip-Hop", title: "Vautours", artist: "Ziak"),
        CuratedTrack(deezerID: 603415762, genre: "House", title: "You Don't Know Me", artist: "Armand van Helden"),
        CuratedTrack(deezerID: 14383880, genre: "Electro", title: "Levels", artist: "Avicii"),
        CuratedTrack(deezerID: 798382542, genre: "House", title: "Baianá", artist: "Bakermat"),
        CuratedTrack(deezerID: 13040252, genre: "Electro", title: "Feel So Close", artist: "Calvin Harris"),
        CuratedTrack(deezerID: 103996098, genre: "Electro", title: "How Deep Is Your Love", artist: "Calvin Harris"),
        CuratedTrack(deezerID: 88936747, genre: "Electro", title: "Summer", artist: "Calvin Harris"),
        CuratedTrack(deezerID: 907649, genre: "House", title: "Gypsy Woman", artist: "Crystal Waters"),
        CuratedTrack(deezerID: 3155977, genre: "Electro", title: "Robot Rock", artist: "Daft Punk"),
        CuratedTrack(deezerID: 1372670872, genre: "Electro", title: "Seven Nation Army", artist: "Dance Fruits Music"),
        CuratedTrack(deezerID: 3348770961, genre: "Electro", title: "Final Countdown 2025", artist: "David Guetta"),
        CuratedTrack(deezerID: 14405161, genre: "Electro", title: "Welcome To St. Tropez", artist: "DJ Antoine"),
        CuratedTrack(deezerID: 1239694902, genre: "House", title: "Marea", artist: "Fred again.."),
        CuratedTrack(deezerID: 2855541182, genre: "Electro", title: "Freed From Desire", artist: "Gala"),
        CuratedTrack(deezerID: 3155984871, genre: "House", title: "My Paradise", artist: "Jamie Jones"),
        CuratedTrack(deezerID: 2100102627, genre: "Electro", title: "We Are Your Friends", artist: "Justice"),
        CuratedTrack(deezerID: 10284909, genre: "Electro", title: "D.A.N.C.E", artist: "Justice"),
        CuratedTrack(deezerID: 721269682, genre: "House", title: "No Rhyme No Reason", artist: "LTJ XPerience"),
        CuratedTrack(deezerID: 15165360, genre: "House", title: "I Follow Rivers", artist: "Lykke Li"),
        CuratedTrack(deezerID: 669567072, genre: "Electro", title: "Summer Days", artist: "Martin Garrix"),
        CuratedTrack(deezerID: 3808859012, genre: "House", title: "Intoxicated", artist: "Martin Solveig"),
        CuratedTrack(deezerID: 373219601, genre: "House", title: "All Stars", artist: "Martin Solveig"),
        CuratedTrack(deezerID: 3639536972, genre: "House", title: "Horny", artist: "Mousse T."),
        CuratedTrack(deezerID: 3155635951, genre: "House", title: "Pushing On", artist: "Oliver $"),
        CuratedTrack(deezerID: 695110932, genre: "Electro", title: "Music Sounds Better With You", artist: "Stardust"),
        CuratedTrack(deezerID: 1484242262, genre: "Electro", title: "Gimme Gimme Gimme", artist: "Syzz"),
        CuratedTrack(deezerID: 78115474, genre: "House", title: "The Bomb!", artist: "The Bucketheads"),
        CuratedTrack(deezerID: 510287882, genre: "House", title: "Later Bitches", artist: "The Prince Karma"),
        CuratedTrack(deezerID: 468390352, genre: "House", title: "Bullit", artist: "Watermät"),
        CuratedTrack(deezerID: 77542036, genre: "House", title: "Faded", artist: "ZHU"),
        CuratedTrack(deezerID: 2170492547, genre: "Reggaeton", title: "Arranca", artist: "Becky G"),
        CuratedTrack(deezerID: 429989292, genre: "Latin", title: "La Vida Es Un Carnaval", artist: "Celia Cruz"),
        CuratedTrack(deezerID: 6, genre: "Reggaeton", title: "Pepas", artist: "Farruko"),
        CuratedTrack(deezerID: 123345682, genre: "Reggaeton", title: "La Gozadera", artist: "Gente De Zona"),
        CuratedTrack(deezerID: 2609095102, genre: "Latin", title: "Te Mata", artist: "Kali Uchis"),
        CuratedTrack(deezerID: 438850292, genre: "Reggaeton", title: "Bum Bum Tam Tam", artist: "MC Fioti"),
        CuratedTrack(deezerID: 671285982, genre: "Latin", title: "Para Que Llorar", artist: "Santi Sanz"),
        CuratedTrack(deezerID: 79589178, genre: "Latin", title: "Loca", artist: "Shakira"),
        CuratedTrack(deezerID: 79589202, genre: "Latin", title: "rabiosa", artist: "shakira ft. pitbull"),
        CuratedTrack(deezerID: 1662709912, genre: "Hip-Hop", title: "Suavemente", artist: "Soolking"),
        CuratedTrack(deezerID: 92719900, genre: "Rock", title: "Highway to Hell", artist: "AC/DC"),
        CuratedTrack(deezerID: 2576769042, genre: "COCOVARIET", title: "Le monde en face", artist: "Ahma Valentine"),
        CuratedTrack(deezerID: 2496474661, genre: "Reggaeton", title: "Mil Veces", artist: "Anitta"),
        CuratedTrack(deezerID: 576851252, genre: "Afro", title: "Pookie", artist: "Aya Nakamura"),
        CuratedTrack(deezerID: 576851222, genre: "Afro", title: "Djadja", artist: "Aya Nakamura"),
        CuratedTrack(deezerID: 1881003417, genre: "Afro", title: "Rush", artist: "Ayra Starr"),
        CuratedTrack(deezerID: 2485118, genre: "R&B", title: "Single Ladies (Put a Ring on It)", artist: "Beyoncé"),
        CuratedTrack(deezerID: 2435238, genre: "Electro", title: "Let's Get It Started", artist: "Black Eyed Peas"),
        CuratedTrack(deezerID: 7375556, genre: "Hip-Hop", title: "Pump It", artist: "Black Eyed Peas"),
        CuratedTrack(deezerID: 772603752, genre: "Reggaeton", title: "RITMO", artist: "Black Eyed Peas"),
        CuratedTrack(deezerID: 136336110, genre: "Pop", title: "24K Magic", artist: "Bruno Mars"),
        CuratedTrack(deezerID: 447098092, genre: "Pop", title: "Havana", artist: "Camila Cabello"),
        CuratedTrack(deezerID: 2147487627, genre: "COCOVARIET", title: "L'amour", artist: "Christophe Maé"),
        CuratedTrack(deezerID: 3231101771, genre: "Pop", title: "Daylight", artist: "David Kushner"),
        CuratedTrack(deezerID: 797228462, genre: "Hip-Hop", title: "Say So", artist: "Doja Cat"),
        CuratedTrack(deezerID: 2433524015, genre: "COCOVARIET", title: "LOVE'n'TENDRESSE", artist: "Eddy de Pretto"),
        CuratedTrack(deezerID: 3030780521, genre: "COCOVARIET", title: "CRASH <3", artist: "Eddy de Pretto"),
        CuratedTrack(deezerID: 4162078, genre: "Hip-Hop", title: "Right Round", artist: "Flo Rida"),
        CuratedTrack(deezerID: 65232772, genre: "Hip-Hop", title: "Good Feeling", artist: "Flo Rida"),
        CuratedTrack(deezerID: 72717420, genre: "Hip-Hop", title: "Bella", artist: "GIMS"),
        CuratedTrack(deezerID: 2405369625, genre: "COCOVARIET", title: "Parapluie", artist: "Jeck"),
        CuratedTrack(deezerID: 2536747241, genre: "COCOVARIET", title: "On verra bien", artist: "Jovan"),
        CuratedTrack(deezerID: 124237488, genre: "Pop", title: "CAN'T STOP THE FEELING!", artist: "Justin Timberlake"),
        CuratedTrack(deezerID: 565127, genre: "Pop", title: "SexyBack", artist: "Justin Timberlake"),
        CuratedTrack(deezerID: 1324559462, genre: "Pop", title: "Iko Iko (My Bestie)", artist: "Justin Wellington"),
        CuratedTrack(deezerID: 135412704, genre: "Afro", title: "Zouk la ce sel médicament nou ni", artist: "Kassav'"),
        CuratedTrack(deezerID: 135203382, genre: "Afro", title: "Chocolat", artist: "Lartiste"),
        CuratedTrack(deezerID: 3528163, genre: "COCOVARIET", title: "Tu m'oublieras", artist: "Larusso"),
        CuratedTrack(deezerID: 12565421, genre: "Electro", title: "Sexy And I Know It", artist: "LMFAO"),
        CuratedTrack(deezerID: 12565420, genre: "Electro", title: "Party Rock Anthem", artist: "LMFAO"),
        CuratedTrack(deezerID: 2166864777, genre: "Pop", title: "Tattoo", artist: "Loreen"),
        CuratedTrack(deezerID: 2485949771, genre: "Pop", title: "Is It Love", artist: "Loreen"),
        CuratedTrack(deezerID: 2290823805, genre: "COCOVARIET", title: "Pardonne-moi", artist: "Louane"),
        CuratedTrack(deezerID: 1953253637, genre: "COCOVARIET", title: "Secret", artist: "Louane"),
        CuratedTrack(deezerID: 623698142, genre: "Reggaeton", title: "Despacito", artist: "Luis Fonsi & Daddy Yankee"),
        CuratedTrack(deezerID: 679217, genre: "Pop", title: "Hung Up", artist: "Madonna"),
        CuratedTrack(deezerID: 2135303217, genre: "Pop", title: "If We Ever Broke Up", artist: "Mae Stephens"),
        CuratedTrack(deezerID: 1242670642, genre: "House", title: "Rasputin", artist: "Majestic"),
        CuratedTrack(deezerID: 4763165, genre: "Pop", title: "Beat It", artist: "Michael Jackson"),
        CuratedTrack(deezerID: 2266742737, genre: "Latin", title: "Ai se eu te pego (nossa nossa)", artist: "MICHEL TELO"),
        CuratedTrack(deezerID: 2425671805, genre: "Pop", title: "C’est la Vie", artist: "MIKA"),
        CuratedTrack(deezerID: 3442901201, genre: "Hip-Hop", title: "Adriano", artist: "Niska"),
        CuratedTrack(deezerID: 2440763155, genre: "Pop", title: "vampire", artist: "Olivia Rodrigo"),
        CuratedTrack(deezerID: 78098991, genre: "Pop", title: "Cheerleader", artist: "OMI"),
        CuratedTrack(deezerID: 2292149325, genre: "Pop", title: "RUNAWAY", artist: "OneRepublic"),
        CuratedTrack(deezerID: 2454947975, genre: "Pop", title: "Mirage (for Assassin's Creed Mirage)", artist: "OneRepublic"),
        CuratedTrack(deezerID: 10308117, genre: "Electro", title: "Give Me Everything", artist: "Pitbull"),
        CuratedTrack(deezerID: 2886526102, genre: "COCOVARIET", title: "Dis Moi Tout", artist: "Ridsa"),
        CuratedTrack(deezerID: 2422952525, genre: "Pop", title: "Single Soon", artist: "Selena Gomez"),
        CuratedTrack(deezerID: 1728081337, genre: "COCOVARIET", title: "Sea, Sex And Sun", artist: "Serge Gainsbourg"),
        CuratedTrack(deezerID: 1890679127, genre: "COCOVARIET", title: "Chez toi", artist: "Slimane"),
        CuratedTrack(deezerID: 1890679137, genre: "COCOVARIET", title: "Des milliers de je t'aime", artist: "Slimane"),
        CuratedTrack(deezerID: 10162588, genre: "Electro", title: "Sweat", artist: "Snoop Dog Feat David Guetta"),
        CuratedTrack(deezerID: 4181750, genre: "Disco", title: "Murder On The Dancefloor", artist: "Sophie Ellis-Bextor"),
        CuratedTrack(deezerID: 3133738, genre: "Pop", title: "Wannabe", artist: "Spice Girls"),
        CuratedTrack(deezerID: 6297555, genre: "COCOVARIET", title: "Alors on danse", artist: "Stromae"),
        CuratedTrack(deezerID: 7860278, genre: "Electro", title: "Cobrastyle", artist: "Teddybears"),
        CuratedTrack(deezerID: 7706014, genre: "Pop", title: "just can't get enough", artist: "the black eyed peas"),
        CuratedTrack(deezerID: 908604612, genre: "Pop", title: "Blinding Lights", artist: "The Weeknd"),
        CuratedTrack(deezerID: 2347250785, genre: "Pop", title: "One Of Your Girls", artist: "Troye Sivan"),
        CuratedTrack(deezerID: 783011442, genre: "Electro", title: "Scream & Shout", artist: "will.i.am"),
        CuratedTrack(deezerID: 904732, genre: "R&B", title: "Respect", artist: "Aretha Franklin"),
        CuratedTrack(deezerID: 3661342592, genre: "Afro", title: "Baby", artist: "Aya Nakamura"),
        CuratedTrack(deezerID: 609244, genre: "R&B", title: "Crazy In Love", artist: "Beyoncé"),
        CuratedTrack(deezerID: 10202476, genre: "Electro", title: "Tonight Im Fucking You (feat. Ludacris)", artist: "Enrique Iglesias"),
        CuratedTrack(deezerID: 613093802, genre: "R&B", title: "Femme Like U", artist: "K-Maro"),
        CuratedTrack(deezerID: 1161679, genre: "R&B", title: "Family Affair", artist: "Mary J. Blige"),
        CuratedTrack(deezerID: 15586242, genre: "R&B", title: "Doo Wop", artist: "Ms. Lauryn Hill"),
        CuratedTrack(deezerID: 14525573, genre: "Pop", title: "Where Have You Been", artist: "Rihanna"),
        CuratedTrack(deezerID: 88897841, genre: "Latin", title: "Hips Don't Lie (Feat. Wyclef Jean)", artist: "Shakira"),
        CuratedTrack(deezerID: 2149221017, genre: "Afro", title: "Room 69", artist: "Tayc"),
        CuratedTrack(deezerID: 837914, genre: "R&B", title: "Yeah!", artist: "Usher"),
        CuratedTrack(deezerID: 62439051, genre: "Electro", title: "Scream & Shout", artist: "Will.I.Am & Britney Spears"),
        CuratedTrack(deezerID: 388714341, genre: "Reggaeton", title: "La Gasolina", artist: "(Reggaeton)Daddy Yankee"),
        CuratedTrack(deezerID: 1122450992, genre: "Reggaeton", title: "DÁKITI", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 667792262, genre: "Reggaeton", title: "Con Calma", artist: "Daddy Yankee"),
        CuratedTrack(deezerID: 716383902, genre: "Reggaeton", title: "Loco Contigo", artist: "DJ Snake"),
        CuratedTrack(deezerID: 716383932, genre: "Electro", title: "Magenta Riddim", artist: "DJ Snake"),
        CuratedTrack(deezerID: 373362011, genre: "Reggaeton", title: "Mi Gente", artist: "J Balvin"),
        CuratedTrack(deezerID: 667004452, genre: "Reggaeton", title: "Mi gente", artist: "J Balvin con Willy William"),
        CuratedTrack(deezerID: 825112142, genre: "Reggaeton", title: "Que Calor", artist: "Major Lazer"),
        CuratedTrack(deezerID: 1841999507, genre: "Reggaeton", title: "DESPECHÁ", artist: "ROSALÍA"),
        CuratedTrack(deezerID: 1298490012, genre: "Reggaeton", title: "Dancing On Dangerous", artist: "Sean Paul"),
        CuratedTrack(deezerID: 14853178, genre: "Rock", title: "Back In Black", artist: "AC/DC"),
        CuratedTrack(deezerID: 2373296565, genre: "Pop", title: "What Was I Made For? [From The Motion Picture \"Barbie\"]", artist: "Billie Eilish"),
        CuratedTrack(deezerID: 4749568, genre: "Rock", title: "Everlong", artist: "Foo Fighters"),
        CuratedTrack(deezerID: 374658067, genre: "Rock", title: "Believer", artist: "Imagine Dragons"),
        CuratedTrack(deezerID: 1809158097, genre: "Rock", title: "Waves", artist: "Imagine Dragons"),
        CuratedTrack(deezerID: 2424631215, genre: "Rock", title: "Children of the Sky (a Starfield song)", artist: "Imagine Dragons"),
        CuratedTrack(deezerID: 3101155, genre: "Rock", title: "Sex On Fire", artist: "Kings Of Leon"),
        CuratedTrack(deezerID: 3100987, genre: "Rock", title: "Use Somebody", artist: "Kings Of Leon"),
        CuratedTrack(deezerID: 2226982417, genre: "Pop", title: "Wish You The Best", artist: "Lewis Capaldi"),
        CuratedTrack(deezerID: 1, genre: "Rock", title: "58 - Måneskin - HONEY (ARE U COMING_)", artist: "Måneskin - HONEY (ARE U COMING_)"),
        CuratedTrack(deezerID: 3628511, genre: "Rock", title: "Supermassive Black Hole", artist: "Muse"),
        CuratedTrack(deezerID: 67753314, genre: "Rock", title: "Smells Like Teen Spirit", artist: "Nirvana"),
        CuratedTrack(deezerID: 2310525, genre: "Rock", title: "Bohemian Rhapsody", artist: "Queen"),
        CuratedTrack(deezerID: 2310521, genre: "Rock", title: "We Will Rock You", artist: "Queen"),
        CuratedTrack(deezerID: 2310537, genre: "Rock", title: "Don't Stop Me Now", artist: "Queen"),
        CuratedTrack(deezerID: 445918, genre: "Rock", title: "Californication", artist: "Red Hot Chili Peppers"),
        CuratedTrack(deezerID: 67238735, genre: "Rock", title: "The Less I Know the Better", artist: "Tame Impala"),
        CuratedTrack(deezerID: 6920011, genre: "Rock", title: "Let's Get Loud", artist: "The Baseballs"),
        CuratedTrack(deezerID: 857453, genre: "Rock", title: "Mr. Brightside", artist: "The Killers"),
        CuratedTrack(deezerID: 1092293262, genre: "Rock", title: "Seven Nation Army", artist: "The White Stripes"),
        CuratedTrack(deezerID: 2416477805, genre: "Rock", title: "Hated", artist: "YUNGBLUD"),
        CuratedTrack(deezerID: 2312090, genre: "COCOVARIET", title: "Tous Les Mêmes", artist: "Stromae"),
        CuratedTrack(deezerID: 67185914, genre: "COCOVARIET", title: "Papaoutai", artist: "Stromae"),
        CuratedTrack(deezerID: 92720934, genre: "COCOVARIET", title: "Formidable", artist: "Stromae"),
        CuratedTrack(deezerID: 13129197, genre: "Disco", title: "Don't Stop 'Til You Get Enough (2003 Edit)", artist: "Michael Jackson"),
        CuratedTrack(deezerID: 62960815, genre: "Disco", title: "Last Night a D.J. Saved My Life", artist: "Indeep"),
        CuratedTrack(deezerID: 9, genre: "Disco", title: "Dancing Queen", artist: "ABBA"),
        CuratedTrack(deezerID: 906568, genre: "Disco", title: "Celebration (Single Version)", artist: "Kool & The Gang"),
        CuratedTrack(deezerID: 691622, genre: "Disco", title: "We Are Family (1995 Remaster)", artist: "Sister Sledge"),
        CuratedTrack(deezerID: 18, genre: "Disco", title: "Never Can Say Goodbye (Single Version)", artist: "Gloria Gaynor"),
        CuratedTrack(deezerID: 76282634, genre: "Disco", title: "Don't Leave Me This Way", artist: "Thelma Houston"),
        CuratedTrack(deezerID: 5, genre: "Disco", title: "I'm Gonna Let My Heart Do The Walking", artist: "The Supremes"),
        CuratedTrack(deezerID: 1027891, genre: "Disco", title: "Got to Be Real", artist: "Cheryl Lynn"),
        CuratedTrack(deezerID: 129771348, genre: "Disco", title: "Let's All Chant", artist: "Michael Zager Band"),
        CuratedTrack(deezerID: 14, genre: "House", title: "Cycles", artist: "CamelPhat"),
        CuratedTrack(deezerID: 215, genre: "House", title: "One Night In Mykonos", artist: "TWOPILOTS"),
        CuratedTrack(deezerID: 24, genre: "House", title: "Seychelles Remix", artist: "Booba"),
        CuratedTrack(deezerID: 4, genre: "House", title: "Can't Slow Down", artist: "Choujaa"),
        CuratedTrack(deezerID: 90, genre: "House", title: "But You Know", artist: "Ginton"),
        CuratedTrack(deezerID: 956, genre: "House", title: "Te Doy La Libertad", artist: "MESTIZA"),
        CuratedTrack(deezerID: 59, genre: "House", title: "Esperar", artist: "ERIICE"),
        CuratedTrack(deezerID: 4762941, genre: "COCOVARIET", title: "J'irai où tu iras (with Jean-Jacques Goldman)", artist: "Céline Dion"),
        CuratedTrack(deezerID: 983238, genre: "COCOVARIET", title: "J't'emmène au vent", artist: "Louise Attaque"),
        CuratedTrack(deezerID: 3135725, genre: "Rock", title: "Ça c'est vraiment toi", artist: "Telephone"),
        CuratedTrack(deezerID: 3156247951, genre: "House", title: "La Verdolaga", artist: "HUGEL"),
        CuratedTrack(deezerID: 2628154112, genre: "House", title: "7 Seconds", artist: "Joezi"),
        CuratedTrack(deezerID: 507548912, genre: "Electro", title: "Inferno", artist: "Carl Cox"),
        CuratedTrack(deezerID: 3076432031, genre: "House", title: "W4U (feat. Jen)", artist: "Mont Rouge"),
        CuratedTrack(deezerID: 3001468701, genre: "Afro", title: "soso (JOSEPH Remix)", artist: "Omah lay"),
        CuratedTrack(deezerID: 2099670727, genre: "House", title: "Miss You (Marten Lou Remix)", artist: "Oliver Tree"),
        CuratedTrack(deezerID: 1668422912, genre: "House", title: "Paris (Chloé Caillet Remix)", artist: "&ME"),
        CuratedTrack(deezerID: 135373112, genre: "House", title: "This Girl (Kungs Vs. Cookin' On 3 Burners) (Kungs Vs. Cookin' On 3 Burners)", artist: "Kungs"),
        CuratedTrack(deezerID: 1372169352, genre: "House", title: "Never Going Home", artist: "Kungs"),
        CuratedTrack(deezerID: 7706008, genre: "Electro", title: "Don’t Stop The Party", artist: "Black Eyed Peas"),
        CuratedTrack(deezerID: 427253282, genre: "Pop", title: "disco tits", artist: "Tove Lo"),
        CuratedTrack(deezerID: 723821422, genre: "House", title: "Shake (Dr Packer Re-Shake)", artist: "Foreal People"),
        CuratedTrack(deezerID: 129139886, genre: "House", title: "The Edge", artist: "Robosonic"),
        CuratedTrack(deezerID: 3049238361, genre: "House", title: "Sunrise Generation (Meera Remix)", artist: "Damian Lazarus"),
        CuratedTrack(deezerID: 1977567857, genre: "House", title: "My City's On Fire (Notre Dame Remix)", artist: "Jimi Jules"),
        CuratedTrack(deezerID: 994464192, genre: "House", title: "Feeling Good", artist: "Javi Colors"),
        CuratedTrack(deezerID: 78304463, genre: "House", title: "The Weekend (Radio Edit)", artist: "Michael Gray"),
        CuratedTrack(deezerID: 505204262, genre: "Electro", title: "In My Mind", artist: "Dynoro"),
        CuratedTrack(deezerID: 1489933842, genre: "House", title: "Because You Move Me", artist: "Tinlicker"),
        CuratedTrack(deezerID: 671464512, genre: "House", title: "Pretty Baby", artist: "Redondo"),
        CuratedTrack(deezerID: 3175052941, genre: "Electro", title: "Exotica", artist: "Gabry Ponte"),
        CuratedTrack(deezerID: 3441858141, genre: "House", title: "Riptide (feat. Ilan Kidron)", artist: "Sigala"),
        CuratedTrack(deezerID: 1178599842, genre: "House", title: "Friday (feat. Mufasa & Hypeman) (Dopamine Re-Edit)", artist: "Nightcrawlers"),
        CuratedTrack(deezerID: 3194135561, genre: "Electro", title: "Walking Away (Infinity)", artist: "Matway"),
        CuratedTrack(deezerID: 910693, genre: "Hip-Hop", title: "Changes", artist: "2Pac"),
        CuratedTrack(deezerID: 1228452582, genre: "House", title: "Fireworks (feat. Moss Kena & The Knocks)", artist: "Purple Disco Machine"),
        CuratedTrack(deezerID: 2044588597, genre: "Disco", title: "Get Down Saturday Night", artist: "Oliver Cheatham"),
        CuratedTrack(deezerID: 2105158337, genre: "Pop", title: "Flowers", artist: "Miley Cyrus"),
        CuratedTrack(deezerID: 17826508, genre: "Pop", title: "Call Me Maybe", artist: "Carly Rae Jepsen"),
        CuratedTrack(deezerID: 437046332, genre: "Rock", title: "Beggin'", artist: "Måneskin"),
        CuratedTrack(deezerID: 118986142, genre: "Pop", title: "Cheap Thrills (feat. Sean Paul)", artist: "Sia"),
        CuratedTrack(deezerID: 3169161, genre: "Pop", title: "I Kissed A Girl", artist: "Katy Perry"),
        CuratedTrack(deezerID: 1575417, genre: "Pop", title: "The Sweet Escape", artist: "Gwen Stefani"),
        CuratedTrack(deezerID: 1855507607, genre: "Pop", title: "American Boy", artist: "Estelle"),
        CuratedTrack(deezerID: 62847144, genre: "Electro", title: "She Wolf (Falling to Pieces) [feat. Sia]", artist: "David Guetta"),
        CuratedTrack(deezerID: 87, genre: "Pop", title: "Stargazing", artist: "Myles Smith"),
        CuratedTrack(deezerID: 916496, genre: "R&B", title: "No Diggity", artist: "Blackstreet"),
        CuratedTrack(deezerID: 375689861, genre: "Hip-Hop", title: "Wild Thoughts (feat. Rihanna & Bryson Tiller)", artist: "DJ Khaled"),
        CuratedTrack(deezerID: 1741494317, genre: "Reggaeton", title: "Tití Me Preguntó", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 64848628, genre: "Latin", title: "Obsesion", artist: "Aventura"),
        CuratedTrack(deezerID: 136341512, genre: "Reggaeton", title: "No Lie", artist: "Sean Paul"),
        CuratedTrack(deezerID: 14948701, genre: "Reggaeton", title: "Danza Kuduro", artist: "Don Omar"),
        CuratedTrack(deezerID: 1685337397, genre: "Reggaeton", title: "LA FAMA", artist: "ROSALÍA"),
        CuratedTrack(deezerID: 123373232, genre: "Electro", title: "Bailar", artist: "Deorro"),
        CuratedTrack(deezerID: 38139, genre: "Pop", title: "Everybody Wants To Rule The World", artist: "Tears for Fears"),
        CuratedTrack(deezerID: 3167843, genre: "Electro", title: "Around the World", artist: "Daft Punk"),
        CuratedTrack(deezerID: 21, genre: "Rock", title: "Wonderwall", artist: "Oasis"),
        CuratedTrack(deezerID: 752155092, genre: "Afro", title: "love nwantiti (ah ah ah)", artist: "CKay"),
        CuratedTrack(deezerID: 2689621452, genre: "Hip-Hop", title: "Dana Dana", artist: "Rima"),
        CuratedTrack(deezerID: 54519711, genre: "Electro", title: "Down The Road", artist: "C2C"),
        CuratedTrack(deezerID: 3507123471, genre: "House", title: "Bulanga", artist: "Felipe Allenn"),
        CuratedTrack(deezerID: 144203048, genre: "House", title: "Call on Me", artist: "Eric Prydz"),
        CuratedTrack(deezerID: 2102633427, genre: "Electro", title: "Animals", artist: "Martin Garrix"),
        CuratedTrack(deezerID: 553056812, genre: "Electro", title: "Just a Little More Love", artist: "David Guetta"),
        CuratedTrack(deezerID: 4619466, genre: "Electro", title: "I Gotta Feeling", artist: "Black Eyed Peas"),
        CuratedTrack(deezerID: 466013612, genre: "Electro", title: "Rattle", artist: "Bingo Players"),
        CuratedTrack(deezerID: 3107326, genre: "Electro", title: "Love Is Gone", artist: "David Guetta"),
        CuratedTrack(deezerID: 68133053, genre: "House", title: "Pursuit of Happiness", artist: "InstaHit Crew"),
        CuratedTrack(deezerID: 1451459162, genre: "Electro", title: "Booyah", artist: "Showtek"),
        CuratedTrack(deezerID: 82564724, genre: "Electro", title: "I'm an Albatraoz", artist: "AronChupa"),
        CuratedTrack(deezerID: 18181530, genre: "House", title: "Pursuit Of Happiness", artist: "Kid Cudi"),
        CuratedTrack(deezerID: 1984836197, genre: "COCOVARIET", title: "Magnolias for Ever", artist: "Claude François"),
        CuratedTrack(deezerID: 3803035232, genre: "House", title: "Hello", artist: "Martin Solveig"),
        CuratedTrack(deezerID: 75819429, genre: "House", title: "One Day (Vandaag)", artist: "Bakermat"),
        CuratedTrack(deezerID: 1134280762, genre: "House", title: "Put Your Hands Up For Detroit", artist: "Fedde Le Grand"),
        CuratedTrack(deezerID: 3156101171, genre: "House", title: "Pump It Up", artist: "Endor"),
        CuratedTrack(deezerID: 38194901, genre: "Pop", title: "Somebody That I Used To Know", artist: "Gotye"),
        CuratedTrack(deezerID: 3808856552, genre: "House", title: "I Want You", artist: "Martin Solveig"),
        CuratedTrack(deezerID: 3434402411, genre: "Electro", title: "Together", artist: "David Guetta"),
        CuratedTrack(deezerID: 3016411391, genre: "Electro", title: "Let's Go", artist: "Jaden Bojsen"),
        CuratedTrack(deezerID: 10296241, genre: "Hip-Hop", title: "Sweat", artist: "Snoop Dogg"),
        CuratedTrack(deezerID: 69170898, genre: "Hip-Hop", title: "Bring the Noise", artist: "Public Enemy"),
        CuratedTrack(deezerID: 650147122, genre: "House", title: "No Stress", artist: "Laurent Wolf"),
        CuratedTrack(deezerID: 87982541, genre: "Electro", title: "San Francisco", artist: "Ph Electro"),
        CuratedTrack(deezerID: 3378403321, genre: "House", title: "Be Your Friend", artist: "Cheat Codes"),
        CuratedTrack(deezerID: 120536314, genre: "Electro", title: "Toop Toop", artist: "Cassius"),
        CuratedTrack(deezerID: 393460732, genre: "Electro", title: "Without You", artist: "Avicii"),
        CuratedTrack(deezerID: 2916188841, genre: "Electro", title: "Free Bird", artist: "MOONLGHT"),
        CuratedTrack(deezerID: 706847, genre: "Pop", title: "Never Ever", artist: "All Saints"),
        CuratedTrack(deezerID: 473274412, genre: "Hip-Hop", title: "Shout!", artist: "The Isley Brothers"),
        CuratedTrack(deezerID: 2122526, genre: "Latin", title: "Boombastic", artist: "Shaggy"),
        CuratedTrack(deezerID: 428850822, genre: "Pop", title: "Good Thing", artist: "Fine Young Cannibals"),
        CuratedTrack(deezerID: 13165731, genre: "Latin", title: "Shy Guy", artist: "Diana King"),
        CuratedTrack(deezerID: 518458142, genre: "Rock", title: "Paradise City", artist: "Guns N' Roses"),
        CuratedTrack(deezerID: 3148646711, genre: "Pop", title: "Rock DJ", artist: "Robbie Williams"),
        CuratedTrack(deezerID: 3153065, genre: "Pop", title: "Bette Davis Eyes", artist: "Kim Carnes"),
        CuratedTrack(deezerID: 2901697491, genre: "House", title: "Les Oies Sauvages", artist: "Yann Muller"),
        CuratedTrack(deezerID: 928969372, genre: "House", title: "Paroles", artist: "Yann Muller"),
        CuratedTrack(deezerID: 1077700822, genre: "Electro", title: "Mr. Saxobeat", artist: "Alexandra Stan"),
        CuratedTrack(deezerID: 1629769072, genre: "Disco", title: "Saturday Hustle", artist: "DiscoGalactiX"),
        CuratedTrack(deezerID: 2589549242, genre: "House", title: "It's Not Right But It's Okay", artist: "Mr. Belt & Wezol"),
        CuratedTrack(deezerID: 2846442802, genre: "Reggaeton", title: "Si Antes Te Hubiera Conocido", artist: "KAROL G"),
        CuratedTrack(deezerID: 2716896732, genre: "Latin", title: "Outro Lugar", artist: "Salomé de Bahia"),
        CuratedTrack(deezerID: 767383202, genre: "Latin", title: "Balada", artist: "Gusttavo Lima"),
        CuratedTrack(deezerID: 886322, genre: "COCOVARIET", title: "Je ne suis pas un héros", artist: "Daniel Balavoine"),
        CuratedTrack(deezerID: 714554, genre: "Rock", title: "Dis-moi", artist: "BB Brunes"),
        CuratedTrack(deezerID: 1619126272, genre: "COCOVARIET", title: "La goffa Lolita", artist: "Vincè la petite culotte"),
        CuratedTrack(deezerID: 2862281, genre: "House", title: "Ça m'énerve", artist: "Helmut Fritz"),
        CuratedTrack(deezerID: 1161020382, genre: "Latin", title: "Danza Kuduro", artist: "Lucenzo"),
        CuratedTrack(deezerID: 1507773472, genre: "Latin", title: "Ateo", artist: "C. Tangana"),
        CuratedTrack(deezerID: 3445820, genre: "Electro", title: "When Love Takes Over", artist: "David Guetta"),
        CuratedTrack(deezerID: 3148168, genre: "Pop", title: "Fuck You", artist: "Lily Allen"),
        CuratedTrack(deezerID: 600886, genre: "COCOVARIET", title: "Place des grands hommes", artist: "Patrick Bruel"),
        CuratedTrack(deezerID: 1149273, genre: "COCOVARIET", title: "Monday, Tuesday... Laissez-moi danser", artist: "Dalida"),
        CuratedTrack(deezerID: 3472539, genre: "Disco", title: "It's Raining Men", artist: "Geri Halliwell"),
        CuratedTrack(deezerID: 3157972, genre: "Pop", title: "Viva La Vida", artist: "Coldplay"),
        CuratedTrack(deezerID: 8011854, genre: "Pop", title: "Marry You", artist: "Bruno Mars"),
        CuratedTrack(deezerID: 576822202, genre: "Hip-Hop", title: "Cosmo", artist: "Soprano"),
        CuratedTrack(deezerID: 911317852, genre: "Pop", title: "Holding Out for a Hero", artist: "Bonnie Tyler"),
        CuratedTrack(deezerID: 2847461482, genre: "COCOVARIET", title: "Dans les yeux d'Émilie", artist: "Romain Ughetto"),
        CuratedTrack(deezerID: 701326562, genre: "Pop", title: "Happy", artist: "Pharrell Williams"),
        CuratedTrack(deezerID: 3256016, genre: "Rock", title: "New York avec toi", artist: "Telephone"),
        CuratedTrack(deezerID: 893594412, genre: "House", title: "Numb", artist: "Elderbrook"),
        CuratedTrack(deezerID: 2858067662, genre: "House", title: "Lovely", artist: "Ikerfoxx"),
        CuratedTrack(deezerID: 2695572412, genre: "House", title: "Intro", artist: "TR3NACRIA"),
        CuratedTrack(deezerID: 2477781041, genre: "House", title: "My Love for You", artist: "Marten Lou"),
        CuratedTrack(deezerID: 3701274662, genre: "House", title: "Havanero", artist: "DJ Jarell"),
        CuratedTrack(deezerID: 2492716331, genre: "House", title: "Miracle", artist: "Adriatique"),
        CuratedTrack(deezerID: 2951106011, genre: "House", title: "Like A Dream", artist: "Adriatique"),
        CuratedTrack(deezerID: 2608551762, genre: "Electro", title: "Past Lives", artist: "sapientdream"),
        CuratedTrack(deezerID: 2720190122, genre: "House", title: "Baddy On The Floor", artist: "Jamie xx"),
        CuratedTrack(deezerID: 3329690381, genre: "House", title: "Yu Feel", artist: "Verb"),
        CuratedTrack(deezerID: 1738774067, genre: "House", title: "Sing It Back", artist: "Dj Hermes"),
        CuratedTrack(deezerID: 966648, genre: "R&B", title: "Wish I Didn't Miss You", artist: "Angie Stone"),
        CuratedTrack(deezerID: 2652885342, genre: "Electro", title: "Tried So Hard", artist: "Youngr"),
        CuratedTrack(deezerID: 3603058412, genre: "House", title: "No Sleep", artist: "Meduza"),
        CuratedTrack(deezerID: 3628883602, genre: "House", title: "Caramelle", artist: "Mesto"),
        CuratedTrack(deezerID: 5747924, genre: "House", title: "Your World", artist: "Benedetto"),
        CuratedTrack(deezerID: 517144922, genre: "Electro", title: "We Are Perfect", artist: "Cristian Marchi"),
        CuratedTrack(deezerID: 3262675101, genre: "Hip-Hop", title: "Anxiety", artist: "Doechii"),
        CuratedTrack(deezerID: 3422267721, genre: "Electro", title: "Desolate Lands", artist: "Adam Beyer"),
        CuratedTrack(deezerID: 3811654872, genre: "Electro", title: "Cambodia", artist: "Agoria"),
        CuratedTrack(deezerID: 580936, genre: "R&B", title: "Say My Name", artist: "Destiny's Child"),
        CuratedTrack(deezerID: 1924639057, genre: "Hip-Hop", title: "STAR WALKIN'", artist: "Lil Nas X"),
        CuratedTrack(deezerID: 1759430967, genre: "Hip-Hop", title: "Meuda", artist: "Tiakola"),
        CuratedTrack(deezerID: 1439691952, genre: "Hip-Hop", title: "INDUSTRY BABY", artist: "Lil Nas X"),
        CuratedTrack(deezerID: 1298524752, genre: "Afro", title: "Jolie madame", artist: "Joé Dwet Filé"),
        CuratedTrack(deezerID: 3102004051, genre: "Hip-Hop", title: "NANANI NANANA", artist: "Gazo"),
        CuratedTrack(deezerID: 2561982012, genre: "Hip-Hop", title: "MAMI WATA", artist: "Gazo"),
        CuratedTrack(deezerID: 1129572462, genre: "Reggaeton", title: "Hawái", artist: "Maluma"),
        CuratedTrack(deezerID: 2326105095, genre: "Latin", title: "Copa Vacía", artist: "Shakira"),
        CuratedTrack(deezerID: 3171003001, genre: "Reggaeton", title: "BAILE INolVIDABLE", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 2044337497, genre: "Afro", title: "KU LO SA", artist: "Oxlade"),
        CuratedTrack(deezerID: 1666673152, genre: "Pop", title: "Bam Bam", artist: "Camila Cabello"),
        CuratedTrack(deezerID: 2200304467, genre: "Reggaeton", title: "BESO", artist: "ROSALÍA"),
        CuratedTrack(deezerID: 532589062, genre: "House", title: "Le temps est bon", artist: "Bon Entendeur"),
        CuratedTrack(deezerID: 1738308487, genre: "Hip-Hop", title: "TOUT VA BIEN", artist: "Alonzo"),
        CuratedTrack(deezerID: 3002724121, genre: "Latin", title: "Soltera", artist: "Shakira"),
        CuratedTrack(deezerID: 2151341427, genre: "Pop", title: "Night Heights", artist: "Jain"),
        CuratedTrack(deezerID: 1455828442, genre: "Electro", title: "Love Me Now", artist: "Kygo"),
        CuratedTrack(deezerID: 1896376597, genre: "Electro", title: "Woke Up in Love", artist: "Kygo"),
        CuratedTrack(deezerID: 1264696562, genre: "Pop", title: "River", artist: "Tom Gregory"),
        CuratedTrack(deezerID: 1855814847, genre: "Pop", title: "Superstar", artist: "Jamelia"),
        CuratedTrack(deezerID: 2304999015, genre: "Reggaeton", title: "COCO LOCO", artist: "Maluma"),
        CuratedTrack(deezerID: 3171003131, genre: "Reggaeton", title: "DtMF", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 415238442, genre: "Pop", title: "What About Us", artist: "P!nk"),
        CuratedTrack(deezerID: 1797297127, genre: "House", title: "BREAK MY SOUL", artist: "Beyoncé"),
        CuratedTrack(deezerID: 3014213321, genre: "Pop", title: "Chacun son chacun", artist: "THEODORT"),
        CuratedTrack(deezerID: 5639255, genre: "Hip-Hop", title: "Wati by Night", artist: "Sexion D'Assaut"),
        CuratedTrack(deezerID: 1842063487, genre: "House", title: "CUFF IT", artist: "Beyoncé"),
        CuratedTrack(deezerID: 3054938751, genre: "Pop", title: "Les démons de minuit", artist: "Julien Doré"),
        CuratedTrack(deezerID: 1595157041, genre: "House", title: "In The Dark", artist: "Purple Disco Machine"),
        CuratedTrack(deezerID: 3548216281, genre: "House", title: "WHERE IS MY HUSBAND!", artist: "Raye"),
        CuratedTrack(deezerID: 3012877461, genre: "Reggaeton", title: "Pasaporte", artist: "Rauw Alejandro"),
        CuratedTrack(deezerID: 2633491932, genre: "House", title: "Basta Cazzate", artist: "Bon Entendeur"),
        CuratedTrack(deezerID: 1458986142, genre: "House", title: "Dopamine", artist: "Purple Disco Machine"),
        CuratedTrack(deezerID: 3171002981, genre: "Reggaeton", title: "NUEVAYoL", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 923740862, genre: "House", title: "Secrets", artist: "Regard"),
        CuratedTrack(deezerID: 1775253117, genre: "Electro", title: "Numb", artist: "Marshmello"),
        CuratedTrack(deezerID: 2751202791, genre: "House", title: "Honey Boy", artist: "Purple Disco Machine"),
        CuratedTrack(deezerID: 2375967015, genre: "Hip-Hop", title: "K-POP", artist: "The Weeknd"),
        CuratedTrack(deezerID: 614756502, genre: "Electro", title: "Giant", artist: "Calvin Harris"),
        CuratedTrack(deezerID: 2120598297, genre: "Pop", title: "TRUSTFALL", artist: "P!nk"),
        CuratedTrack(deezerID: 1283987962, genre: "Latin", title: "A Un Paso De La Luna", artist: "Reik"),
        CuratedTrack(deezerID: 770293952, genre: "House", title: "Roses", artist: "SAINt JHN"),
        CuratedTrack(deezerID: 3889748961, genre: "House", title: "Jamaican", artist: "HUGEL"),
        CuratedTrack(deezerID: 2179672997, genre: "Electro", title: "The Magic Key", artist: "Trinix"),
        CuratedTrack(deezerID: 2872998762, genre: "Hip-Hop", title: "Monaco", artist: "Guy2bezbar"),
        CuratedTrack(deezerID: 542335432, genre: "Electro", title: "Promises", artist: "Calvin Harris"),
        CuratedTrack(deezerID: 2216851977, genre: "Electro", title: "Esta Vida", artist: "Marshmello"),
        CuratedTrack(deezerID: 741480472, genre: "House", title: "Turn Me On", artist: "Riton"),
        CuratedTrack(deezerID: 2370741815, genre: "Pop", title: "Makeba", artist: "Jain"),
        CuratedTrack(deezerID: 2083091847, genre: "Electro", title: "Work With My Love", artist: "Alok"),
        CuratedTrack(deezerID: 2712022541, genre: "House", title: "In My Bones", artist: "Lost Frequencies"),
        CuratedTrack(deezerID: 3067533781, genre: "Electro", title: "Looking For Love", artist: "Alok"),
        CuratedTrack(deezerID: 1408344462, genre: "Pop", title: "Un beso de improviso", artist: "Ana Mena"),
        CuratedTrack(deezerID: 1506996362, genre: "Reggaeton", title: "El Incomprendido", artist: "Farruko"),
        CuratedTrack(deezerID: 2660815532, genre: "Electro", title: "Lovers In A Past Life", artist: "Calvin Harris"),
        CuratedTrack(deezerID: 1787751117, genre: "Pop", title: "LAS 12", artist: "Ana Mena"),
        CuratedTrack(deezerID: 3502053411, genre: "Electro", title: "QUE CE SOIT CLAIR", artist: "Paul Kalkbrenner"),
        CuratedTrack(deezerID: 1960232517, genre: "Latin", title: "Monotonía", artist: "Shakira"),
        CuratedTrack(deezerID: 414838122, genre: "Hip-Hop", title: "Basique", artist: "Orelsan"),
        CuratedTrack(deezerID: 2454933765, genre: "Pop", title: "Madrid City", artist: "Ana Mena"),
        CuratedTrack(deezerID: 1286520172, genre: "Electro", title: "I Wanna Dance with Somebody", artist: "Hard Lights"),
        CuratedTrack(deezerID: 1151063132, genre: "Rock", title: "Trois nuits par semaine", artist: "Indochine"),
        CuratedTrack(deezerID: 2840316722, genre: "Rock", title: "Le chant des cygnes", artist: "Indochine"),
        CuratedTrack(deezerID: 3026960801, genre: "Electro", title: "Not Alone", artist: "Gabry Ponte"),
        CuratedTrack(deezerID: 2182322087, genre: "Electro", title: "Miracle", artist: "Calvin Harris"),
        CuratedTrack(deezerID: 15391618, genre: "Pop", title: "Toxic", artist: "Britney Spears"),
        CuratedTrack(deezerID: 2289342455, genre: "Reggaeton", title: "WHERE SHE GOES", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 1847938107, genre: "Hip-Hop", title: "Miss You", artist: "Southstar"),
        CuratedTrack(deezerID: 3454677991, genre: "Pop", title: "JUMP", artist: "BLACKPINK"),
        CuratedTrack(deezerID: 596537, genre: "COCOVARIET", title: "Dans les yeux d'Émilie", artist: "Joe Dassin"),
        CuratedTrack(deezerID: 2621151252, genre: "House", title: "POWER", artist: "Marnik"),
        CuratedTrack(deezerID: 2802379712, genre: "House", title: "Cocorito", artist: "Marnik"),
        CuratedTrack(deezerID: 2712128861, genre: "Electro", title: "Pedro", artist: "Jaxomy"),
        CuratedTrack(deezerID: 3558373981, genre: "Hip-Hop", title: "melodrama", artist: "disiz"),
        CuratedTrack(deezerID: 8146902, genre: "Rock", title: "Footloose", artist: "Kenny Loggins"),
        CuratedTrack(deezerID: 3278913111, genre: "Electro", title: "Soleil Bleu", artist: "Bleu Soleil"),
        CuratedTrack(deezerID: 3045169941, genre: "Hip-Hop", title: "CIEL", artist: "GIMS"),
        CuratedTrack(deezerID: 576851242, genre: "Afro", title: "Copines", artist: "Aya Nakamura"),
        CuratedTrack(deezerID: 3650665212, genre: "Pop", title: "ONE TRACK MIND", artist: "Naïka"),
        CuratedTrack(deezerID: 831196, genre: "R&B", title: "Human Nature", artist: "Michael Jackson"),
        CuratedTrack(deezerID: 3938003381, genre: "Afro", title: "GIRLFRIEND", artist: "Tayc"),
        CuratedTrack(deezerID: 4045817471, genre: "Pop", title: "hate that i made you love me", artist: "Ariana Grande"),
        CuratedTrack(deezerID: 3760706922, genre: "Pop", title: "La lune", artist: "Christophe Maé"),
        CuratedTrack(deezerID: 144389048, genre: "Pop", title: "Lush Life", artist: "Zara Larsson"),
        CuratedTrack(deezerID: 3814069442, genre: "Pop", title: "Comme Caroline", artist: "Zaho"),
        CuratedTrack(deezerID: 4047900401, genre: "Hip-Hop", title: "NETFLIX CHILL", artist: "Zola"),
        CuratedTrack(deezerID: 4030914551, genre: "COCOVARIET", title: "C'est à qui le tour", artist: "Mylène Farmer"),
        CuratedTrack(deezerID: 3867905101, genre: "R&B", title: "I Just Might", artist: "Bruno Mars"),
        CuratedTrack(deezerID: 3869647201, genre: "Pop", title: "FEVER DREAM", artist: "Alex Warren"),
        CuratedTrack(deezerID: 3979681391, genre: "Hip-Hop", title: "18 Carats", artist: "Alonzo"),
        CuratedTrack(deezerID: 2424911405, genre: "Pop", title: "Feel Good", artist: "Charlotte Cardin"),
        CuratedTrack(deezerID: 3060824431, genre: "Hip-Hop", title: "FASHION DESIGNA", artist: "Theodora"),
        CuratedTrack(deezerID: 3210709941, genre: "Pop", title: "Ordinary", artist: "Alex Warren"),
        CuratedTrack(deezerID: 3827212511, genre: "Electro", title: "What You Want", artist: "Angèle"),
        CuratedTrack(deezerID: 3602108062, genre: "Hip-Hop", title: "MON BÉBÉ", artist: "RnBoi"),
        CuratedTrack(deezerID: 3818963601, genre: "Rock", title: "Dracula", artist: "Tame Impala"),
        CuratedTrack(deezerID: 3884482901, genre: "Hip-Hop", title: "Picasso", artist: "Bigflo & Oli"),
        CuratedTrack(deezerID: 3862146611, genre: "Hip-Hop", title: "Tu dors ?", artist: "PLK"),
        CuratedTrack(deezerID: 4015341011, genre: "Latin", title: "Dai Dai", artist: "Shakira"),
        CuratedTrack(deezerID: 3571311501, genre: "Pop", title: "La recette", artist: "Jeck"),
        CuratedTrack(deezerID: 3674551372, genre: "Hip-Hop", title: "OG", artist: "Genezio"),
        CuratedTrack(deezerID: 4603408, genre: "Disco", title: "Billie Jean", artist: "Michael Jackson"),
        CuratedTrack(deezerID: 3503857201, genre: "Pop", title: "Man I Need", artist: "Olivia Dean"),
        CuratedTrack(deezerID: 3732618262, genre: "Hip-Hop", title: "AVEC MOI", artist: "RnBoi"),
        CuratedTrack(deezerID: 75867418, genre: "Hip-Hop", title: "J'oublie tout", artist: "Jul"),
        CuratedTrack(deezerID: 4013762661, genre: "Hip-Hop", title: "Le monde est à moi", artist: "Jul"),
        CuratedTrack(deezerID: 701987352, genre: "Hip-Hop", title: "Sous la lune", artist: "Jul"),
        CuratedTrack(deezerID: 4034126871, genre: "Pop", title: "Été avec toi", artist: "Adèle Castillon"),
        CuratedTrack(deezerID: 3401257811, genre: "Hip-Hop", title: "RUINART", artist: "R2"),
        CuratedTrack(deezerID: 767071002, genre: "Hip-Hop", title: "La bandite", artist: "Jul"),
        CuratedTrack(deezerID: 3412534581, genre: "Pop", title: "Golden", artist: "HUNTR/X"),
        CuratedTrack(deezerID: 1426733732, genre: "Hip-Hop", title: "C'est la cité", artist: "Jul"),
        CuratedTrack(deezerID: 3987094421, genre: "Hip-Hop", title: "FEU VERT", artist: "ISS"),
        CuratedTrack(deezerID: 3484365861, genre: "Hip-Hop", title: "PARISIENNE", artist: "GIMS"),
        CuratedTrack(deezerID: 3862146511, genre: "Hip-Hop", title: "Pocahontas", artist: "PLK"),
        CuratedTrack(deezerID: 3579685431, genre: "Pop", title: "The Fate of Ophelia", artist: "Taylor Swift"),
        CuratedTrack(deezerID: 3294048841, genre: "Hip-Hop", title: "Paris", artist: "Nono La Grinta"),
        CuratedTrack(deezerID: 4013762651, genre: "Hip-Hop", title: "C'est dur d'aimer", artist: "Jul"),
        CuratedTrack(deezerID: 4043072601, genre: "Hip-Hop", title: "YAKUZA", artist: "RK"),
        CuratedTrack(deezerID: 3835893541, genre: "Hip-Hop", title: "ELLE VOULAIT", artist: "RnBoi"),
        CuratedTrack(deezerID: 3629572332, genre: "Hip-Hop", title: "BLOQUÉ", artist: "GIMS"),
        CuratedTrack(deezerID: 3469521671, genre: "Hip-Hop", title: "Tour du monde", artist: "Soolking"),
        CuratedTrack(deezerID: 3899366101, genre: "Hip-Hop", title: "À l'aise", artist: "TRIANGLE DES BERMUDES"),
        CuratedTrack(deezerID: 3758716202, genre: "Hip-Hop", title: "SPA", artist: "GIMS"),
        CuratedTrack(deezerID: 37027991, genre: "Electro", title: "Beauty And A Beat", artist: "Justin Bieber"),
        CuratedTrack(deezerID: 3675222292, genre: "Hip-Hop", title: "méli-mélo", artist: "kulturr"),
        CuratedTrack(deezerID: 3850680281, genre: "Electro", title: "New Religion", artist: "Bebe Rexha"),
        CuratedTrack(deezerID: 3921078891, genre: "Hip-Hop", title: "RENÉ CAOVILLA", artist: "Gambi"),
        CuratedTrack(deezerID: 4000152541, genre: "Hip-Hop", title: "Avion de chasse", artist: "Zeg P"),
        CuratedTrack(deezerID: 4047736081, genre: "Hip-Hop", title: "Kendall", artist: "Booba"),
        CuratedTrack(deezerID: 4045099331, genre: "Pop", title: "Maladie", artist: "Mauvais Djo"),
        CuratedTrack(deezerID: 3499178151, genre: "Pop", title: "Pilé", artist: "Mauvais Djo"),
        CuratedTrack(deezerID: 3935276381, genre: "Hip-Hop", title: "Soleil", artist: "GIMS"),
        CuratedTrack(deezerID: 3579710801, genre: "Hip-Hop", title: "LOVE YOU", artist: "Nono La Grinta"),
        CuratedTrack(deezerID: 3837291721, genre: "Hip-Hop", title: "Argent Sale", artist: "La Rvfleuze"),
        CuratedTrack(deezerID: 3784724892, genre: "House", title: "Talk To You", artist: "ANOTR"),
        CuratedTrack(deezerID: 3911003931, genre: "Hip-Hop", title: "PARLU", artist: "La Rvfleuze"),
        CuratedTrack(deezerID: 3314018771, genre: "Hip-Hop", title: "Phénoménal", artist: "Jul"),
        CuratedTrack(deezerID: 3899366131, genre: "Hip-Hop", title: "Balek", artist: "TRIANGLE DES BERMUDES"),
        CuratedTrack(deezerID: 2846025562, genre: "Hip-Hop", title: "Hakayet", artist: "VEN1"),
        CuratedTrack(deezerID: 3330178491, genre: "Hip-Hop", title: "KYKY2BONDY", artist: "Hamza"),
        CuratedTrack(deezerID: 410780162, genre: "Hip-Hop", title: "Parfum quartier", artist: "Jul"),
        CuratedTrack(deezerID: 600108042, genre: "Hip-Hop", title: "Asalto", artist: "Jul"),
        CuratedTrack(deezerID: 3412611901, genre: "Pop", title: "Gabriela", artist: "KATSEYE"),
        CuratedTrack(deezerID: 3977159061, genre: "Hip-Hop", title: "Pangor", artist: "Djaksparo"),
        CuratedTrack(deezerID: 3995047821, genre: "Afro", title: "Sexy Nana", artist: "Aya Nakamura"),
        CuratedTrack(deezerID: 3651885972, genre: "Pop", title: "Soirée mondaine", artist: "Oria"),
        CuratedTrack(deezerID: 3380338381, genre: "Hip-Hop", title: "ZOU BISOU", artist: "Theodora"),
        CuratedTrack(deezerID: 3809346722, genre: "Hip-Hop", title: "B.M.S", artist: "Rambo Goyard"),
        CuratedTrack(deezerID: 3884172321, genre: "Hip-Hop", title: "Miss Kitoko", artist: "Theodora"),
        CuratedTrack(deezerID: 1899060227, genre: "Pop", title: "End of Beginning", artist: "Djo"),
        CuratedTrack(deezerID: 3356310051, genre: "Afro", title: "Baddies", artist: "Aya Nakamura"),
        CuratedTrack(deezerID: 3842413311, genre: "Hip-Hop", title: "Sex Model", artist: "PLK"),
        CuratedTrack(deezerID: 3848530521, genre: "Hip-Hop", title: "Self Aware", artist: "Temper City"),
        CuratedTrack(deezerID: 3591983602, genre: "Hip-Hop", title: "Génération impolie", artist: "Franglish"),
        CuratedTrack(deezerID: 7818900, genre: "Rock", title: "Paint It, Black", artist: "The Rolling Stones"),
        CuratedTrack(deezerID: 1143625, genre: "Rock", title: "Boys Don't Cry", artist: "The Cure"),
        CuratedTrack(deezerID: 5094040, genre: "Rock", title: "I Write Sins Not Tragedies", artist: "Panic! At the Disco"),
        CuratedTrack(deezerID: 432946872, genre: "Rock", title: "Loser", artist: "Beck"),
        CuratedTrack(deezerID: 62082829, genre: "Rock", title: "Killing In The Name", artist: "Rage Against the Machine"),
        CuratedTrack(deezerID: 987064552, genre: "Rock", title: "Live Forever", artist: "Oasis"),
        CuratedTrack(deezerID: 725837, genre: "Rock", title: "Give It Away", artist: "Red Hot Chili Peppers"),
        CuratedTrack(deezerID: 1079668, genre: "Pop", title: "Africa", artist: "Toto"),
        CuratedTrack(deezerID: 773367, genre: "Rock", title: "American Idiot", artist: "Green Day"),
        CuratedTrack(deezerID: 985704102, genre: "Rock", title: "Whatever", artist: "Oasis"),
        CuratedTrack(deezerID: 1143637, genre: "Rock", title: "Lullaby", artist: "The Cure"),
        CuratedTrack(deezerID: 3081706951, genre: "Rock", title: "I Love Rock 'N Roll", artist: "Joan Jett and the Blackhearts"),
        CuratedTrack(deezerID: 870041, genre: "Rock", title: "Teenage Dirtbag", artist: "Wheatus"),
        CuratedTrack(deezerID: 116348610, genre: "Pop", title: "Help!", artist: "The Beatles"),
        CuratedTrack(deezerID: 1085497, genre: "Hip-Hop", title: "No Sleep Till Brooklyn", artist: "Beastie Boys"),
        CuratedTrack(deezerID: 70322132, genre: "Rock", title: "R U Mine?", artist: "Arctic Monkeys"),
        CuratedTrack(deezerID: 137233986, genre: "Rock", title: "The Kids Aren't Alright", artist: "The Offspring"),
        CuratedTrack(deezerID: 1565010, genre: "Rock", title: "All Star", artist: "Smash Mouth"),
        CuratedTrack(deezerID: 4315684, genre: "Rock", title: "Take Me Out", artist: "Franz Ferdinand"),
        CuratedTrack(deezerID: 994702, genre: "Hip-Hop", title: "Walk This Way", artist: "Run-DMC"),
        CuratedTrack(deezerID: 378236081, genre: "Rock", title: "New Noise", artist: "Refused"),
        CuratedTrack(deezerID: 1037414, genre: "Rock", title: "More Than a Feeling", artist: "Boston"),
        CuratedTrack(deezerID: 67503793, genre: "Rock", title: "Another One Bites The Dust", artist: "Queen"),
        CuratedTrack(deezerID: 677232, genre: "Rock", title: "Numb", artist: "Linkin Park"),
        CuratedTrack(deezerID: 69962764, genre: "Rock", title: "Should I Stay or Should I Go", artist: "The Clash"),
        CuratedTrack(deezerID: 678044, genre: "Rock", title: "Basket Case", artist: "Green Day"),
        CuratedTrack(deezerID: 3121608, genre: "Disco", title: "Heart Of Glass", artist: "Blondie"),
        CuratedTrack(deezerID: 565656032, genre: "Pop", title: "Let's Dance", artist: "David Bowie"),
        CuratedTrack(deezerID: 619310, genre: "Pop", title: "The Final Countdown", artist: "Europe"),
        CuratedTrack(deezerID: 1483825212, genre: "Rock", title: "Enter Sandman", artist: "Metallica"),
        CuratedTrack(deezerID: 518458092, genre: "Rock", title: "Welcome To The Jungle", artist: "Guns N' Roses"),
        CuratedTrack(deezerID: 1108061, genre: "Rock", title: "Smooth Criminal", artist: "Alien Ant Farm"),
        CuratedTrack(deezerID: 3102130, genre: "Rock", title: "Song 2", artist: "Blur"),
        CuratedTrack(deezerID: 97098410, genre: "Rock", title: "Jump", artist: "Van Halen"),
        CuratedTrack(deezerID: 912458972, genre: "Rock", title: "Bangin in Your Stereo", artist: "Massive Wagons"),
        CuratedTrack(deezerID: 2525877, genre: "Rock", title: "Roxanne", artist: "The Police"),
        CuratedTrack(deezerID: 1455296862, genre: "Rock", title: "I WANNA BE YOUR SLAVE", artist: "Måneskin"),
        CuratedTrack(deezerID: 3786091892, genre: "Rock", title: "Teenage Kicks", artist: "The Undertones"),
        CuratedTrack(deezerID: 378310131, genre: "Rock", title: "Hate To Say I Told You So", artist: "The Hives"),
        CuratedTrack(deezerID: 2947342, genre: "Rock", title: "Somebody Told Me", artist: "The Killers"),
        CuratedTrack(deezerID: 3129407, genre: "Pop", title: "Feel Good Inc.", artist: "Gorillaz"),
        CuratedTrack(deezerID: 1515437352, genre: "Rock", title: "MAMMAMIA", artist: "Måneskin"),
        CuratedTrack(deezerID: 3105736, genre: "Rock", title: "Goo Goo Muck", artist: "The Cramps"),
        CuratedTrack(deezerID: 137233982, genre: "Rock", title: "Pretty Fly", artist: "The Offspring"),
        CuratedTrack(deezerID: 3248376, genre: "Rock", title: "My Sharona", artist: "The Knack"),
        CuratedTrack(deezerID: 60742395, genre: "Rock", title: "God Save The Queen", artist: "Sex Pistols"),
        CuratedTrack(deezerID: 378299591, genre: "Rock", title: "Come Out and Play", artist: "The Offspring"),
        CuratedTrack(deezerID: 936899, genre: "Rock", title: "Where Is My Mind?", artist: "Pixies"),
        CuratedTrack(deezerID: 7179758, genre: "Rock", title: "No One Knows", artist: "Queens of the Stone Age"),
        CuratedTrack(deezerID: 725971, genre: "Rock", title: "Can't Stop", artist: "Red Hot Chili Peppers"),
        CuratedTrack(deezerID: 17542457, genre: "Rock", title: "Alright", artist: "Supergrass"),
        CuratedTrack(deezerID: 1182048, genre: "Rock", title: "Dimension", artist: "Wolfmother"),
        CuratedTrack(deezerID: 846669, genre: "Rock", title: "Love Is Only a Feeling", artist: "The Darkness"),
        CuratedTrack(deezerID: 2205120, genre: "Rock", title: "Shoot the Runner", artist: "Kasabian"),
        CuratedTrack(deezerID: 3786707482, genre: "Latin", title: "Como en el Idilio", artist: "Marc Anthony"),
        CuratedTrack(deezerID: 3773003372, genre: "Latin", title: "CAMBIARÉ", artist: "Luis Fonsi"),
        CuratedTrack(deezerID: 3086954711, genre: "Latin", title: "Cosa Nuestra", artist: "Rauw Alejandro"),
        CuratedTrack(deezerID: 429987972, genre: "Latin", title: "Ven Devórame Otra Vez", artist: "Lalo Rodriguez"),
        CuratedTrack(deezerID: 3725958682, genre: "Latin", title: "Por un Pendejo no se llora", artist: "Manuel Turizo"),
        CuratedTrack(deezerID: 3171003141, genre: "Latin", title: "LA MuDANZA", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 3783834412, genre: "Latin", title: "1+1", artist: "Maluma"),
        CuratedTrack(deezerID: 3345133651, genre: "Latin", title: "DROGA", artist: "Mora"),
        CuratedTrack(deezerID: 3594145862, genre: "Latin", title: "A CABALLO", artist: "Nathy Peluso"),
        CuratedTrack(deezerID: 3200740371, genre: "Latin", title: "Caramelito", artist: "Guaynaa"),
        CuratedTrack(deezerID: 2432863185, genre: "Latin", title: "ELLA TIENE", artist: "Nathy Peluso"),
        CuratedTrack(deezerID: 3847734401, genre: "Latin", title: "Mi Romi", artist: "Los Yakis"),
        CuratedTrack(deezerID: 3580630881, genre: "Latin", title: "La Tirana", artist: "Mon Laferte"),
        CuratedTrack(deezerID: 3677908682, genre: "Latin", title: "Dardos", artist: "Romeo Santos"),
        CuratedTrack(deezerID: 3628872132, genre: "Latin", title: "La Clave", artist: "Sergio Alejandro"),
        CuratedTrack(deezerID: 3249934031, genre: "Latin", title: "EROTIKA", artist: "Nathy Peluso"),
        CuratedTrack(deezerID: 3710982182, genre: "Latin", title: "Solo", artist: "De La Ghetto"),
        CuratedTrack(deezerID: 3012594991, genre: "Latin", title: "Traicionera", artist: "Daviles de Novelda"),
        CuratedTrack(deezerID: 3759550622, genre: "Latin", title: "Pa' Los Envidiosos", artist: "Pitbull"),
        CuratedTrack(deezerID: 2124708237, genre: "Latin", title: "La Fórmula", artist: "Maluma"),
        CuratedTrack(deezerID: 3310961601, genre: "Latin", title: "How Deep Is Your Love", artist: "Prince Royce"),
        CuratedTrack(deezerID: 3623635112, genre: "Latin", title: "bachata mía", artist: "Elsa y Elmar"),
        CuratedTrack(deezerID: 2747766841, genre: "Latin", title: "EL CANTANTE DEL GHETTO", artist: "Ryan Castro"),
        CuratedTrack(deezerID: 3713785802, genre: "Latin", title: "Playa Pantaleta", artist: "Rawayana"),
        CuratedTrack(deezerID: 3098627101, genre: "Latin", title: "Sigueme Besando Asi", artist: "Manuel Turizo"),
        CuratedTrack(deezerID: 3675376612, genre: "Latin", title: "Qué Tiene Él", artist: "Moa Rivera"),
        CuratedTrack(deezerID: 2965383531, genre: "Latin", title: "Tu Loca", artist: "NATTI NATASHA   "),
        CuratedTrack(deezerID: 1236513632, genre: "Latin", title: "Un Veneno", artist: "C. Tangana"),
        CuratedTrack(deezerID: 2706005432, genre: "Latin", title: "Brindo Con Agua", artist: "Aventura"),
        CuratedTrack(deezerID: 1753549417, genre: "Latin", title: "La Bachata", artist: "Manuel Turizo"),
        CuratedTrack(deezerID: 2659738222, genre: "Latin", title: "En Esta Boca", artist: "Kany Garcia"),
        CuratedTrack(deezerID: 2610617372, genre: "Latin", title: "COMO YO TE QUIERO (DELUXE)", artist: "KHEA"),
        CuratedTrack(deezerID: 2131841797, genre: "Latin", title: "Herrera", artist: "YEИDRY"),
        CuratedTrack(deezerID: 3774754952, genre: "Latin", title: "Solo Tú", artist: "Valeria Jasso"),
        CuratedTrack(deezerID: 3840450261, genre: "Latin", title: "Bachatón", artist: "Mar Lucas"),
        CuratedTrack(deezerID: 2840850382, genre: "Latin", title: "Si Quieres Volver", artist: "Ralphy Dreamz"),
        CuratedTrack(deezerID: 3244282881, genre: "Latin", title: "Mamipuladora", artist: "Mushkaa"),
        CuratedTrack(deezerID: 114622734, genre: "Latin", title: "En Barranquilla Me Quedo", artist: "Joe Arroyo"),
        CuratedTrack(deezerID: 2812852392, genre: "Latin", title: "Quiéreme Menos", artist: "NATTI NATASHA   "),
        CuratedTrack(deezerID: 2891517542, genre: "Latin", title: "Dime tú", artist: "Danny Ocean"),
        CuratedTrack(deezerID: 2884478152, genre: "Latin", title: "Iguales y diferentes", artist: "Lorena Gomez"),
        CuratedTrack(deezerID: 2637953342, genre: "Latin", title: "SIN TI", artist: "GIMS"),
        CuratedTrack(deezerID: 3359783531, genre: "Latin", title: "samaná", artist: "Mau y Ricky"),
        CuratedTrack(deezerID: 2988957391, genre: "Latin", title: "Duro De Verdad pt.2", artist: "Los Sufridos"),
        CuratedTrack(deezerID: 3690691972, genre: "Latin", title: "ROMÁNTICA", artist: "Maria Becerra"),
        CuratedTrack(deezerID: 2732379571, genre: "Latin", title: "Una Vida Pasada", artist: "Camilo"),
        CuratedTrack(deezerID: 2584580172, genre: "Latin", title: "Ahora Que No Te Tengo", artist: "Chanel"),
        CuratedTrack(deezerID: 2169294337, genre: "Latin", title: "El Merengue", artist: "Marshmello"),
        CuratedTrack(deezerID: 2637475742, genre: "Latin", title: "UNA BACHATA", artist: "Lola Indigo"),
        CuratedTrack(deezerID: 686098802, genre: "Latin", title: "Pedro Navaja", artist: "Willie Colón"),
        CuratedTrack(deezerID: 2216800257, genre: "Latin", title: "Solo Pienso En Ti", artist: "Elvis Crespo"),
        CuratedTrack(deezerID: 3637926292, genre: "Latin", title: "Si Te Preguntan", artist: "Salsa Power Band"),
        CuratedTrack(deezerID: 12694767, genre: "Latin", title: "Y No Hago Mas Na'", artist: "El Gran Combo"),
        CuratedTrack(deezerID: 2461353085, genre: "Latin", title: "Rueda Durísimo", artist: "Nandy Versátil"),
        CuratedTrack(deezerID: 2276362, genre: "Latin", title: "La Vida Es Un Carnaval", artist: "Celia Cruz"),
        CuratedTrack(deezerID: 2511434161, genre: "Latin", title: "Plutón", artist: "Arcangel"),
        CuratedTrack(deezerID: 3640116732, genre: "Latin", title: "Bebezinho", artist: "Bianca Costa"),
        CuratedTrack(deezerID: 2122382007, genre: "Latin", title: "Desnúdate", artist: "Zion & Lennox"),
        CuratedTrack(deezerID: 675919592, genre: "Latin", title: "Parecen Viernes", artist: "Marc Anthony"),
        CuratedTrack(deezerID: 6123964, genre: "Latin", title: "La rebelion", artist: "Joe Arroyo"),
        CuratedTrack(deezerID: 13182317, genre: "Latin", title: "La Quiero A Morir", artist: "D.L.G."),
        CuratedTrack(deezerID: 547759, genre: "Latin", title: "Tu Amor Me Hace Bien", artist: "Marc Anthony"),
        CuratedTrack(deezerID: 686082682, genre: "Latin", title: "El Cantante", artist: "Héctor Lavoe"),
        CuratedTrack(deezerID: 523114932, genre: "Latin", title: "Me Tengo Que Ir", artist: "Los Adolescentes"),
        CuratedTrack(deezerID: 1079887762, genre: "Latin", title: "PURO VENENO", artist: "Nathy Peluso"),
        CuratedTrack(deezerID: 3669229822, genre: "Latin", title: "RAMÉ", artist: "Boza"),
        CuratedTrack(deezerID: 3911167911, genre: "Latin", title: "PA' LO BONITO", artist: "Lenny Tavarez"),
        CuratedTrack(deezerID: 3871739701, genre: "Pop", title: "ALGO TÚ", artist: "Shakira"),
        CuratedTrack(deezerID: 3865096921, genre: "Reggaeton", title: "Tonto", artist: "J Balvin"),
        CuratedTrack(deezerID: 3981853831, genre: "Latin", title: "LA GRACIOSA", artist: "Quevedo"),
        CuratedTrack(deezerID: 3421452651, genre: "Reggaeton", title: "Tropicoqueta", artist: "KAROL G"),
        CuratedTrack(deezerID: 3879862701, genre: "Latin", title: "PONGO", artist: "Rvssian"),
        CuratedTrack(deezerID: 3241972661, genre: "Latin", title: "La Plena (W Sound 05)", artist: "W Sound"),
        CuratedTrack(deezerID: 3879273701, genre: "Reggaeton", title: "Una Aventura", artist: "Ozuna"),
        CuratedTrack(deezerID: 3936484551, genre: "Latin", title: "BIAF <3", artist: "Young Miko"),
        CuratedTrack(deezerID: 3407512021, genre: "Latin", title: "TU VAS SIN (fav)", artist: "Rels B"),
        CuratedTrack(deezerID: 3171003121, genre: "Reggaeton", title: "EoO", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 3920012581, genre: "Reggaeton", title: "Pal Agua", artist: "J Balvin"),
        CuratedTrack(deezerID: 3849394771, genre: "Latin", title: "Ayer La Vi (BPA26)", artist: "Juan Magan"),
        CuratedTrack(deezerID: 3663852612, genre: "Pop", title: "Hips Don't Lie", artist: "Shakira"),
        CuratedTrack(deezerID: 2638201552, genre: "Latin", title: "Gata Only", artist: "FloyyMenor"),
        CuratedTrack(deezerID: 3638389092, genre: "Reggaeton", title: "Daddy Yankee: Bzrp Music Sessions, Vol. 0/66", artist: "Bizarrap"),
        CuratedTrack(deezerID: 3640140952, genre: "Reggaeton", title: "La Perla", artist: "ROSALÍA"),
        CuratedTrack(deezerID: 3947383241, genre: "Latin", title: "De Lejitos", artist: "Jay Wheeler"),
        CuratedTrack(deezerID: 3421452481, genre: "Reggaeton", title: "Papasito", artist: "KAROL G"),
        CuratedTrack(deezerID: 3713785742, genre: "Latin", title: "Inglés En Miami", artist: "Rawayana"),
        CuratedTrack(deezerID: 3348923451, genre: "Latin", title: "malibU", artist: "Rusowsky"),
        CuratedTrack(deezerID: 3905162121, genre: "Latin", title: "Pinterest (Spanish)", artist: "Anitta"),
        CuratedTrack(deezerID: 3909037631, genre: "Latin", title: "TRANKAITO", artist: "Feid"),
        CuratedTrack(deezerID: 3171003021, genre: "Reggaeton", title: "WELTiTA", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 3862522561, genre: "Latin", title: "Apambichao", artist: "Manuel Turizo"),
        CuratedTrack(deezerID: 3086954731, genre: "Reggaeton", title: "Qué Pasaría...", artist: "Rauw Alejandro"),
        CuratedTrack(deezerID: 3829058471, genre: "Latin", title: "Choque", artist: "Bad Gyal"),
        CuratedTrack(deezerID: 3729422322, genre: "Latin", title: "daño", artist: "Peso Pluma"),
        CuratedTrack(deezerID: 3380325281, genre: "Latin", title: "SUPERESTRELLA", artist: "Aitana"),
        CuratedTrack(deezerID: 3729422272, genre: "Latin", title: "dopamina", artist: "Peso Pluma"),
        CuratedTrack(deezerID: 3393136571, genre: "Latin", title: "Shiny", artist: "Easykid"),
        CuratedTrack(deezerID: 2403815945, genre: "Reggaeton", title: "QLONA", artist: "KAROL G"),
        CuratedTrack(deezerID: 2496106371, genre: "Reggaeton", title: "MONACO", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 3619889162, genre: "Reggaeton", title: "Berghain", artist: "ROSALÍA"),
        CuratedTrack(deezerID: 3210670571, genre: "Latin", title: "ROMEO", artist: "Anitta"),
        CuratedTrack(deezerID: 3721301952, genre: "Latin", title: "Muévelo", artist: "Kali Uchis"),
        CuratedTrack(deezerID: 3562510031, genre: "Latin", title: "Bodega Baddie", artist: "Cardi B"),
        CuratedTrack(deezerID: 2381974745, genre: "Latin", title: "Una Noche en Medellín", artist: "Cris MJ"),
        CuratedTrack(deezerID: 3353337101, genre: "Latin", title: "no tiene sentido", artist: "Beele"),
        CuratedTrack(deezerID: 3005912441, genre: "Latin", title: "Cuando No Era Cantante", artist: "El Bogueto"),
        CuratedTrack(deezerID: 2154046577, genre: "Reggaeton", title: "AMARGURA", artist: "KAROL G"),
        CuratedTrack(deezerID: 3613707422, genre: "Latin", title: "LA VILLA", artist: "Ryan Castro"),
        CuratedTrack(deezerID: 3694837562, genre: "Latin", title: "HOY SE GUAYA", artist: "Arcangel"),
        CuratedTrack(deezerID: 2565307142, genre: "Latin", title: "LUNA", artist: "Feid"),
        CuratedTrack(deezerID: 2725148591, genre: "Latin", title: "Santa", artist: "Rvssian"),
        CuratedTrack(deezerID: 3431134971, genre: "Electro", title: "Noventa", artist: "DJ Snake"),
        CuratedTrack(deezerID: 3729101662, genre: "Latin", title: "Ay Dale", artist: "Farruko"),
        CuratedTrack(deezerID: 3086954821, genre: "Reggaeton", title: "Khé?", artist: "Rauw Alejandro"),
        CuratedTrack(deezerID: 2710627572, genre: "Latin", title: "DUMBAI", artist: "CA7RIEL & Paco Amoroso"),
        CuratedTrack(deezerID: 3348923391, genre: "Latin", title: "Johnny Glamour", artist: "Rusowsky"),
        CuratedTrack(deezerID: 3543288831, genre: "Latin", title: "Posso Até Não Te Dar Flores", artist: "DJ Japa NK"),
        CuratedTrack(deezerID: 3346909081, genre: "Latin", title: "Vaitimbora", artist: "Trinix"),
        CuratedTrack(deezerID: 3644302002, genre: "Latin", title: "lençóis maranhenses", artist: "Beele"),
        CuratedTrack(deezerID: 2352913965, genre: "Reggaeton", title: "DILUVIO", artist: "Rauw Alejandro"),
        CuratedTrack(deezerID: 3100867631, genre: "Latin", title: "mi refe", artist: "Beele"),
        CuratedTrack(deezerID: 3184783941, genre: "Latin", title: "Corazón Puro", artist: "Rvfv"),
        CuratedTrack(deezerID: 668529022, genre: "Latin", title: "La Cartera", artist: "Farruko"),
        CuratedTrack(deezerID: 3128448851, genre: "Reggaeton", title: "EL CLúB", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 2352899405, genre: "Latin", title: "QUEMA", artist: "Ryan Castro"),
        CuratedTrack(deezerID: 2454704515, genre: "Latin", title: "BUBALU", artist: "Feid"),
        CuratedTrack(deezerID: 3080231821, genre: "Latin", title: "capaz (merengueton)", artist: "alleh"),
        CuratedTrack(deezerID: 3177818391, genre: "Latin", title: "Angelito", artist: "Bad Gyal"),
        CuratedTrack(deezerID: 2971960441, genre: "Latin", title: "Alibi Pt. 2 (with Anitta, Pabllo Vittar & Yseult)", artist: "Sevdaliza"),
        CuratedTrack(deezerID: 3644297482, genre: "Electro", title: "GUAYANDO", artist: "Major Lazer"),
        CuratedTrack(deezerID: 2986885311, genre: "Latin", title: "Después De La 1", artist: "Cris MJ"),
        CuratedTrack(deezerID: 3104740921, genre: "Latin", title: "SHIBATTO", artist: "Quevedo"),
        CuratedTrack(deezerID: 3061738201, genre: "Latin", title: "Imagínate", artist: "Danny Ocean"),
        CuratedTrack(deezerID: 3070117621, genre: "Reggaeton", title: "Cosas Pendientes", artist: "Maluma"),
        CuratedTrack(deezerID: 3654880132, genre: "Latin", title: "1204", artist: "De la rose"),
        CuratedTrack(deezerID: 2927624581, genre: "Latin", title: "TAMBIÉN", artist: "Myke Towers"),
        CuratedTrack(deezerID: 2788486652, genre: "Latin", title: "REAL GANGSTA LOVE", artist: "Trueno"),
        CuratedTrack(deezerID: 2925907271, genre: "Latin", title: "Alegría", artist: "Tiago PZK"),
        CuratedTrack(deezerID: 2824575332, genre: "Latin", title: "OHNANA", artist: "Kapo"),
        CuratedTrack(deezerID: 3064639361, genre: "Latin", title: "Bing Bong", artist: "Yailin la Mas Viral"),
        CuratedTrack(deezerID: 3003099991, genre: "Latin", title: "Q U E V A S H A C E R H O Y ?", artist: "Omar Courtz"),
        CuratedTrack(deezerID: 3345133671, genre: "Latin", title: "AURORA", artist: "Mora"),
        CuratedTrack(deezerID: 2570877172, genre: "Latin", title: "BELLAKEO", artist: "Peso Pluma"),
        CuratedTrack(deezerID: 3079892761, genre: "Latin", title: "Pa’ Qué Volviste?", artist: "Elena Rose"),
        CuratedTrack(deezerID: 2164743217, genre: "Latin", title: "La Bebe (Remix)", artist: "Yng Lvcas"),
        CuratedTrack(deezerID: 3145770261, genre: "Latin", title: "una noche", artist: "alleh"),
        CuratedTrack(deezerID: 2074439067, genre: "Latin", title: "Yandel 150", artist: "Yandel"),
        CuratedTrack(deezerID: 2595262972, genre: "Latin", title: "Una Foto Remix (feat. Emilia)", artist: "Mesita"),
        CuratedTrack(deezerID: 2758436071, genre: "Latin", title: "ADIVINO", artist: "Myke Towers"),
        CuratedTrack(deezerID: 1811481707, genre: "Latin", title: "Quevedo: Bzrp Music Sessions, Vol. 52/66", artist: "Bizarrap"),
        CuratedTrack(deezerID: 2496106541, genre: "Reggaeton", title: "PERRO NEGRO", artist: "Bad Bunny"),
        CuratedTrack(deezerID: 3024269221, genre: "Latin", title: "Qué Pecao", artist: "Manuel Turizo"),
        CuratedTrack(deezerID: 3210598411, genre: "Latin", title: "São Paulo", artist: "The Weeknd"),
        CuratedTrack(deezerID: 2835962342, genre: "Latin", title: "LA REINA", artist: "Lola Indigo"),
        CuratedTrack(deezerID: 2729119091, genre: "Latin", title: "offline", artist: "Young Miko"),
        CuratedTrack(deezerID: 2939590111, genre: "Latin", title: "UWAIE", artist: "Kapo"),
        CuratedTrack(deezerID: 1917168057, genre: "Reggaeton", title: "PUNTO 40", artist: "Rauw Alejandro"),
        CuratedTrack(deezerID: 3524679161, genre: "Latin", title: "COMO OREO", artist: "Blessd"),
        CuratedTrack(deezerID: 3422751531, genre: "Latin", title: "Me Mareo", artist: "Kidd Voodoo"),
        CuratedTrack(deezerID: 3382134521, genre: "Latin", title: "YO y TÚ", artist: "Ovy On The Drums"),
        CuratedTrack(deezerID: 3739682752, genre: "Reggaeton", title: "J Balvin: Bzrp Music Sessions, Vol. 62/66", artist: "Bizarrap"),
    ]
