import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import Party from '../../models/Party.js';
import communityRouter, { activeRestriction, registerReport, resolveReportedContent, communityAccessGuard } from '../../routes/party-community.js';

test('one warning per distinct content, escalation, rate limits and scoped expiration',()=>{
  const reports=[];const input={reporterId:'a',targetId:'b',kind:'photo',contentId:'one',reason:'privacy'};
  const one=registerReport(reports,input,1000000);assert.equal(one.warningNumber,1);assert.equal(one.status,'warned');
  assert.throws(()=>registerReport(reports,{...input,reporterId:'c'}),/déjà/);
  const two=registerReport(reports,{...input,contentId:'two'},1000001);assert.equal(two.status,'needs_review');
  registerReport(reports,{...input,contentId:'three'},1000002);
  assert.throws(()=>registerReport(reports,{...input,contentId:'four'},1000003),/Attends/);
  const until=new Date(1000).toISOString();assert.ok(activeRestriction([{userId:'b',kind:'temporary',until}],'b',999));assert.equal(activeRestriction([{userId:'b',kind:'temporary',until}],'b',1000),null);
  assert.equal(activeRestriction([{userId:'b',kind:'permanent'}],'a'),null);
  assert.ok(activeRestriction([{userId:'b',kind:'permanent'}],'b'));
  const party={participants:[{userId:'b'},{userId:'h',isHost:true}],messages:[{id:'m',authorUserId:'b'},{id:'h',authorUserId:'h'}]};
  assert.equal(resolveReportedContent(party,'message','m').author.userId,'b');assert.equal(resolveReportedContent(party,'message','h').author.userId,'h');
});

test('private inbox isolation, actual content ownership, host decisions and access revocation',async()=>{
  const alice={userId:'a',id:'sa',name:'Alice',sessionToken:'token-a',connected:true};
  const bob={userId:'b',id:'sb',name:'Bob',sessionToken:'token-b',connected:true};
  const p={leaderboard:[{id:"Bob",name:"Bob",points:12}],code:'ABC123',hostSecret:'secret-host',participants:[alice,bob,{userId:'h',id:'sh',name:'Host',isHost:true}],messages:[{id:'m1',authorUserId:'b',message:'word'},{id:'m2',authorUserId:'b',message:'second'}],photos:[],suggestions:[{id:"s1",guestId:"b",title:"Song",artist:"Artist",status:"queued"}],guestVotes:{sb:{Song:"fire"}},trackHistory:[{id:"played1",title:"Earlier",artist:"Artist",requestedBy:{guestId:"b"}},{title:"Song",artist:"Artist"}]};
  const doc={communityLikes:[],communityReports:[],communityRestrictions:[],privateMessages:[]}; const events=[];
  const PhotoModel={async updateOne(){}};
  const PartyModel={findOne(){return{select(){return this},async lean(){return structuredClone(doc)}}},async updateOne(q,u){
    for(const [key,value] of Object.entries(u.$push||{}))doc[key].push(structuredClone(value));
    if(u.$addToSet?.communityLikes&&!doc.communityLikes.some(x=>JSON.stringify(x)===JSON.stringify(u.$addToSet.communityLikes)))doc.communityLikes.push(u.$addToSet.communityLikes);
    if(u.$pull?.communityLikes)doc.communityLikes=doc.communityLikes.filter(x=>JSON.stringify(x)!==JSON.stringify(u.$pull.communityLikes));
    if(u.$set?.communityRestrictions)doc.communityRestrictions=structuredClone(u.$set.communityRestrictions);
    if(u.$set?.['communityReports.$[r].status'])doc.communityReports.forEach(r=>r.status='reviewed');
    if(u.$pull?.communityRestrictions)doc.communityRestrictions=doc.communityRestrictions.filter(x=>x.userId!==u.$pull.communityRestrictions.userId);
  }};
  const io={to(room){return{emit(event,data){events.push({room,event,data})}}},sockets:{sockets:new Map()}};
  const app=express();app.use(express.json());app.use('/api/party',communityRouter({parties:new Map([[p.code,p]]),io,PartyModel,PhotoModel,enrichProfile:async()=>({photoURL:'https://example.com/profile.jpg'}),buildLightState:()=>({code:p.code}),authenticate:async()=>{throw new Error('bad jwt')}}));
  const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
  const url=`http://127.0.0.1:${server.address().port}/api/party/ABC123/community`;
  const request=async(path='',body,headers={'X-Guest-Session':'token-a'})=>{const r=await fetch(url+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()}};
  try{
    assert.equal((await request('',undefined,{})).status,403);
    assert.equal((await request('',undefined,{Authorization:'Bearer invalid'})).status,401);
    assert.equal((await request('/decision',{userId:'b',action:'permanent'})).status,403);
    assert.equal((await request('/like',{kind:'message',contentId:'missing',liked:true})).status,400);
    assert.equal((await request('/like',{kind:'message',contentId:'m1',liked:true})).status,200);
    await request('/like',{kind:'message',contentId:'m1',liked:true});
    let profile=(await request('/touch/b')).body;
    assert.equal(profile.messages[0].likeCount,1);assert.equal(profile.messages[0].liked,true);
    assert.equal(profile.person.photoURL,'https://example.com/profile.jpg');assert.equal(profile.ranking.position,1);assert.equal(profile.ranking.points,12);assert.ok(profile.songs.some(x=>x.title==='Earlier'&&x.status==='played'));assert.equal(profile.favorites[0].title,'Song');assert.equal(profile.songs[0].status,'played');assert.equal(profile.songs[0].canBoost,false);
    bob.previousSocketIds=['old-bob'];
    p.guestVotes['old-bob']={Legacy:'fire',current:'fire'};
    p.photos.push({id:'legacy-photo',guestId:'old-bob',url:'https://example.com/legacy.jpg'});
    p.suggestions.push({id:'legacy-song',authorUserId:'obsolete',guestId:'b',title:'Pending',artist:'Artist',status:'pending'});
    const recovered=(await request('/touch/b')).body;
    assert.ok(recovered.favorites.some(x=>x.title==='Legacy'));
    assert.ok(recovered.favorites.every(x=>x.title!=='current'));
    assert.ok(recovered.photos.some(x=>x.id==='legacy-photo'));
    assert.ok(recovered.songs.some(x=>x.id==='legacy-song'));
    const other=(await request('/touch/a')).body;
    assert.equal(other.photos.length,0);assert.equal(other.favorites.length,0);assert.equal(other.songs.length,0);
    p.photos=[];
    assert.equal((await request('/touch/a')).body.isOwn,true);
    assert.equal((await request('/touch/b',undefined,{'X-Guest-Session':'token-b'})).body.songs[0].canBoost,false);
    const hostTouch=await request('/touch/h',undefined,{'X-Host-Secret':'secret-host'});
    assert.equal(hostTouch.status,200);assert.equal(hostTouch.body.isOwn,true);
    const hostVisiting=await request('/touch/b',undefined,{'X-Host-Secret':'secret-host'});
    assert.equal(hostVisiting.status,200);assert.equal(hostVisiting.body.isOwn,false);
    assert.equal(hostVisiting.body.songs[0].canBoost,false);
    assert.equal((await request('/like',{kind:'message',contentId:'m1',liked:true},{'X-Host-Secret':'secret-host'})).status,200);
    assert.equal((await request('/touch/b',undefined,{'X-Host-Secret':'secret-host'})).body.messages[0].liked,true);
    await request('/like',{kind:'message',contentId:'m1',liked:false},{'X-Host-Secret':'secret-host'});

    await request('/like',{kind:'message',contentId:'m1',liked:false});assert.equal((await request('/touch/b')).body.messages[0].likeCount,0);

    bob.connected=false;
    assert.equal((await request('/message',{targetId:'b',text:'Private hello'})).status,200,'A temporarily disconnected participant still receives persisted messages');
    bob.departedAt=new Date().toISOString();
    assert.equal((await request('/message',{targetId:'b',text:'No longer present'})).status,400);
    delete bob.departedAt;bob.connected=true;
    assert.equal((await request()).body.messages.length,1);
    assert.equal((await request('',undefined,{'X-Host-Secret':'secret-host'})).body.messages.length,0);
    assert.equal((await request('/message',{targetId:'b',text:'Host hello'},{'X-Host-Secret':'secret-host'})).status,200);
    assert.equal((await request('',undefined,{'X-Guest-Session':'token-b'})).body.messages.length,2);
    assert.equal((await request()).body.messages.length,1, 'Alice cannot read host-to-Bob conversation');
    assert.equal((await request('/message',{targetId:'h',text:'Reply to host'},{'X-Guest-Session':'token-b'})).status,200);
    assert.equal((await request('',undefined,{'X-Host-Secret':'secret-host'})).body.messages.length,2);

    assert.equal((await request('/report',{kind:'message',contentId:'missing',reason:'inappropriate'})).status,400);
    assert.equal((await request('/report',{kind:'message',contentId:'m1',reason:'inappropriate'})).status,200);
    assert.match(events.find(e=>e.event==='community:warning').data.message,/Ton message a été signalé/);
    const privateWarning=events.find(e=>e.event==='community:warning');assert.equal(privateWarning.room,'sb');assert.equal(privateWarning.data.reporterId,undefined);
    assert.equal((await request('/report',{kind:'message',contentId:'m1',reason:'inappropriate'})).status,400);
    assert.equal((await request('/report',{kind:'message',contentId:'m2',reason:'inappropriate'})).status,200);
    assert.ok(events.find(e=>e.event==='community:alert'&&e.room==='host:ABC123'));
    assert.equal((await request()).body.alerts.length,0);
    assert.equal((await request('',undefined,{'X-Host-Secret':'secret-host'})).body.alerts.length,1);
    const ownWarnings=(await request('',undefined,{'X-Guest-Session':'token-b'})).body.warnings;
    assert.equal(ownWarnings.length,2);
    assert.equal(ownWarnings[0].excerpt,'word');
    assert.equal(ownWarnings[0].reason,'inappropriate');
    assert.equal(ownWarnings[0].reporterId,undefined);
    assert.equal((await request()).body.warnings.length,0);
    p.photos.push({id:'host-photo',authorUserId:'h',url:'https://example.com/photo.jpg',caption:'Host photo'});
    const hostPhoto=(await request('/reportable')).body.items.find(x=>x.id==='host-photo');
    assert.equal(hostPhoto.url,'https://example.com/photo.jpg');
    assert.equal(hostPhoto.userId,'h');
    assert.equal((await request('/report',{kind:'photo',contentId:'host-photo',reason:'privacy'})).status,200);
    const hostWarnings=(await request('',undefined,{'X-Host-Secret':'secret-host'})).body.warnings;
    assert.equal(hostWarnings.length,1);
    assert.equal(hostWarnings[0].url,hostPhoto.url);
    assert.equal(hostWarnings[0].reporterId,undefined);
    assert.equal(hostWarnings[0].canManage,true);
    assert.equal((await request('/reported-content',{reportId:hostWarnings[0].id,action:'remove'})).status,403);
    assert.equal((await request('/reported-content',{reportId:hostWarnings[0].id,action:'remove'},{'X-Host-Secret':'secret-host'})).status,200);
    assert.equal(p.photos.length,0);
    const bobReport=ownWarnings[0].id;
    assert.equal((await request('/reported-content',{reportId:bobReport,action:'edit',text:'Changed by stranger'})).status,403);
    assert.equal((await request('/reported-content',{reportId:bobReport,action:'edit',text:'  '},{'X-Guest-Session':'token-b'})).status,400);
    assert.equal((await request('/reported-content',{reportId:bobReport,action:'edit',text:'Message corrigé'},{'X-Guest-Session':'token-b'})).status,200);
    assert.equal(p.messages[0].message,'Message corrigé');
    assert.ok(events.some(e=>e.event==='messages:update'&&e.room==='guest:ABC123'));
    assert.equal((await request('/reported-content',{reportId:bobReport,action:'remove'},{'X-Guest-Session':'token-b'})).status,200);
    assert.equal(p.messages.some(m=>m.id==='m1'),false);
    assert.equal((await request('',undefined,{'X-Guest-Session':'token-b'})).body.warnings[0].canManage,false);
    p.photos=[];
    assert.equal((await request('/moderation/b')).status,403);
    const dossier=await request('/moderation/b',undefined,{'X-Host-Secret':'secret-host'});
    assert.equal(dossier.status,200);assert.equal(dossier.body.incidents.length,2);
    assert.equal(dossier.body.incidents[0].reporterId,undefined);
    const touch=await request('/touch/b');assert.equal(touch.status,200);
    assert.equal(touch.body.incidents,undefined);assert.equal(touch.body.restriction,undefined);
    const reportable=await request('/reportable');assert.equal(reportable.status,200);
    assert.ok(reportable.body.items.every(x=>x.name==='Bob'));
    assert.equal((await request('/decision',{userId:'b',action:'temporary'},{'X-Host-Secret':'secret-host'})).status,200);
    assert.equal(doc.communityRestrictions[0].kind,'temporary');assert.ok(new Date(doc.communityRestrictions[0].until)>new Date(Date.now()+890000));
    assert.equal((await request('/message',{targetId:'a',text:'cannot send'},{'X-Guest-Session':'token-b'})).status,403);
    assert.equal((await request('/decision',{userId:'h',action:'permanent'},{'X-Host-Secret':'secret-host'})).status,400);
    assert.equal((await request('/decision',{userId:'b',action:'restore'},{'X-Host-Secret':'secret-host'})).status,200);assert.equal(doc.communityRestrictions.length,0);
    assert.ok(bob.departedAt); // Permission to return does not pretend the guest has returned.
  } finally {server.closeAllConnections();await new Promise(r=>server.close(r));}
});

test('private data excluded from generic party reads and admission guard handles expiration',async()=>{
  for(const field of ['privateMessages','communityReports','communityRestrictions'])assert.equal(Party.schema.path(field).options.select,false);
  let restrictions=[{userId:'a',kind:'temporary',until:new Date(Date.now()+900000).toISOString()}];
  const PartyModel={findOne(){return{select(){return this},async lean(){return{communityRestrictions:restrictions,participants:[{userId:'a',departedAt:new Date().toISOString()}]}}}}};
  const guard=communityAccessGuard({parties:new Map(),PartyModel,authenticate:async()=>({_id:'a'})});
  async function check(path){let status=null,passed=false;const req={method:'POST',path,headers:{authorization:'Bearer valid'},body:{}};const res={status(n){status=n;return this},json(){}};await guard(req,res,()=>{passed=true});return{status,passed};}
  assert.equal((await check('/ABC123/request-join')).status,403);
  restrictions=[{userId:'a',kind:'temporary',until:new Date(Date.now()-1).toISOString()}];
  assert.equal((await check('/ABC123/request-join')).passed,true);
  assert.equal((await check('/ABC123/suggest')).status,403);
});
